import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { highlightCode, renderMarkdown } from '../src/syntax.js';
import { calendarDays, dateValue, parseDate, parseTime, timeValue, wrapNumber } from '../src/calendar.js';
import { iconNames, extraIcons } from '../src/icon-names.js';
import { primaryTheme, setBrandTheme } from '../src/theme.js';
import { placePopover } from '../src/helpers.js';
import { componentCatalog, patternCatalog } from '../examples/catalog.js';
import { icons as lucideIcons } from 'lucide';

const workspaceCheck = spawnSync(process.execPath, ['test/workspace-card.mjs'], { encoding: 'utf8' });
assert.equal(workspaceCheck.status, 0, workspaceCheck.stderr);

const illustrationCheck = spawnSync(process.execPath, ['test/empty-illustration.mjs'], { encoding: 'utf8' });
assert.equal(illustrationCheck.status, 0, illustrationCheck.stderr);

const components = (await readdir('src/components')).filter((file) => file.endsWith('.js'));
const examplePages = (await readdir('examples')).filter((file) => file.endsWith('.html'));
const entry = await readFile('src/index.js', 'utf8');
const docsIndex = await readFile('docs/index.md', 'utf8');

for (const file of components) {
  assert.match(entry, new RegExp(`components/${file.replace('.', '\\.')}`), `${file} is not exported`);
  await readFile(`docs/${file.replace('.js', '.md')}`, 'utf8');
  assert.doesNotMatch(await readFile(`src/components/${file}`, 'utf8'), /required/, `${file} must not expose required validation`);
  const check = spawnSync(process.execPath, ['--check', `src/components/${file}`], { encoding: 'utf8' });
  assert.equal(check.status, 0, check.stderr);
}

for (const file of components) assert.match(docsIndex, new RegExp(`\\(${file.replace('.js', '')}\\.md\\)`), `${file} is missing from the docs index`);
assert.match(docsIndex, /\(theme\.md\)/, 'theme docs are missing from the docs index');

assert.equal(spawnSync(process.execPath, ['--check', 'src/index.js']).status, 0);
assert.doesNotMatch(await readFile('src/native-input.js', 'utf8'), /required/, 'native inputs must not expose required validation');
assert.equal(spawnSync(process.execPath, ['--check', 'dist/simple-elements.js']).status, 0);
assert.match(await readFile('dist/simple-elements.js', 'utf8'), /const connectChoice =/, 'shared choice renderer must be included in the browser bundle');
assert.match(await readFile('dist/simple-elements.js', 'utf8'), /globalThis\.SimpleElements = \{ setBrandTheme, registerIcons \}/, 'browser bundle must expose the theme setter');
assert.match(entry, /setBrandTheme/);
const generatedTheme = primaryTheme('#2563eb');
assert.equal(generatedTheme.light.base, '#2563eb');
assert.notEqual(generatedTheme.light.hover, generatedTheme.light.base);
assert.notEqual(generatedTheme.dark.base, generatedTheme.light.base);
const luminance = (hex) => hex.slice(1).match(/../g).map((channel) => parseInt(channel, 16) / 255)
  .map((channel) => channel <= .04045 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4)
  .reduce((sum, channel, index) => sum + channel * [.2126, .7152, .0722][index], 0);
const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + .05) / (Math.min(luminance(a), luminance(b)) + .05);
const themeCss = await readFile('src/styles.css', 'utf8');
const darkTokens = Object.fromEntries([...themeCss.match(/\[data-theme="dark"\] \{([^}]+)\}/)[1].matchAll(/--se-([\w-]+): (#[\da-f]{6});/g)].map(([, role, hex]) => [role, hex]));
const darkSurfaces = ['bg', 'surface', 'surface-soft', 'surface-raised'].map((role) => darkTokens[role]);
for (const surface of darkSurfaces) {
  for (const role of ['text', 'muted', 'faint']) assert.ok(contrast(darkTokens[role], surface) >= 4.5, `${role} must remain readable on ${surface}`);
  assert.ok(contrast(darkTokens['border-strong'], surface) >= 3, 'control outlines need 3:1 contrast');
}
assert.ok(darkSurfaces.every((surface, index) => index === 0 || luminance(surface) > luminance(darkSurfaces[index - 1])), 'raised dark surfaces must become lighter');
for (const tone of ['danger', 'success', 'warning', 'info', 'important']) assert.ok(contrast(darkTokens[tone], darkTokens[`${tone}-soft`]) >= 4.5, `${tone} status text must be readable`);
for (const r of ['00', '33', '66', '99', 'cc', 'ff']) for (const g of ['00', '33', '66', '99', 'cc', 'ff']) for (const b of ['00', '33', '66', '99', 'cc', 'ff']) {
  const primary = `#${r}${g}${b}`;
  const { dark, light } = primaryTheme(primary);
  assert.equal(light.base, primary, 'light brand colors must stay unchanged');
  for (const fill of [dark.base, dark.hover]) assert.ok(contrast(dark.contrast, fill) >= 4.5, `brand button text: ${primary}`);
  for (const surface of [...darkSurfaces, dark.soft]) assert.ok(contrast(dark.base, surface) >= 4.5, `brand links: ${primary} on ${surface}`);
  assert.ok(contrast(dark.text, dark.soft) >= 4.5, `brand badge text: ${primary}`);
}
for (const [role, value] of Object.entries(generatedTheme.dark)) assert.ok(themeCss.includes(`--se-primary-dark${role === 'base' ? '' : `-${role}`}: ${value};`), `CSS and runtime dark ${role} must agree`);
assert.deepEqual(primaryTheme().light, {
  base: '#2563eb',
  hover: '#1e58d7',
  soft: '#e8f0ff',
  text: '#1e58d7',
  border: '#c4d3ef',
  deep: '#1649b7',
  contrast: '#ffffff',
});
assert.equal(primaryTheme('#abc').light.base, '#aabbcc');
const themeStyles = {};
globalThis.document = { documentElement: { style: { setProperty: (name, value) => { themeStyles[name] = value; } } } };
setBrandTheme({ primary: '#7c3aed' });
assert.equal(themeStyles['--se-primary-light'], '#7c3aed');
assert.equal(themeStyles['--se-primary-dark'], primaryTheme('#7c3aed').dark.base);
delete globalThis.document;
const compiledCss = await readFile('dist/styles.css', 'utf8');
assert.match(compiledCss, /\.se-button/);
assert.match(compiledCss, /\[hidden\]/);
assert.match(compiledCss, /\.se-choice--switch/);
assert.doesNotMatch(compiledCss, /se-choice--light-dark/, 'checkbox and radio styles must not include theme controls');
assert.match(compiledCss, /\.se-theme--segmented/, 'theme switch variants must be compiled');
assert.match(compiledCss, /#f59e0b/, 'theme controls must retain the sun color');
assert.match(compiledCss, /#60a5fa/, 'theme controls must retain the moon color');
assert.match(compiledCss, /textarea:read-only\{[^}]*resize:none/);
assert.match(compiledCss, /se-code\[block\]\[wrap\]/);
assert.match(compiledCss, /se-code-editor\[wrap\]/);
assert.match(compiledCss, /--se-surface-raised:#292d33/, 'dark overlay surface must be compiled');
assert.match(compiledCss, /se-sidebar\[layout-mode=responsive\]\{[^}]*position:absolute/, 'mobile sidebars must overlay page content');
assert.match(compiledCss, /se-sidebar\[overlay\][^{]*\{[^}]*position:absolute/, 'overlay sidebars must leave page content in place while open, closing, or collapsed');
assert.match(compiledCss, /se-sidebar\[layout-mode=responsive\] \[data-sidebar-collapse\]\{display:none/, 'mobile sidebars must hide desktop collapse controls');
assert.match(compiledCss, /se-topbar>\[data-mobile-search\]:not\(\[hidden\]\)\{[^}]*position:absolute/, 'mobile search must overlay page content');
assert.match(compiledCss, /\[layout-mode=desktop-only\][^{]*\{display:none/, 'desktop-only content must be hidden on mobile');
assert.doesNotMatch(compiledCss, /@import\s/);
const selectSource = await readFile('src/components/select.js', 'utf8');
assert.match(selectSource, /const trigger = multiple/);
assert.match(selectSource, /option\.icon/);
assert.match(selectSource, /set value\(value\)/);
assert.match(selectSource, /hasAttribute\('clearable'\)/);
assert.match(selectSource, /const clearable = !multiple/);
assert.match(selectSource, /this\._selected\.clear\(\)/);
const inputSource = await readFile('src/components/input.js', 'utf8');
assert.match(inputSource, /email: \{ placeholder: 'you@example\.com', icon: 'mail' \}/);
assert.match(inputSource, /tel: \{ placeholder: 'Enter a phone number\.\.\.', icon: 'phone' \}/);
assert.match(inputSource, /static defaultsFor\(type = 'text'\)/);
assert.match(inputSource, /error && type !== 'password'/, 'password errors must not overlap the visibility toggle');
const buttonSource = await readFile('src/components/button.js', 'utf8');
assert.match(buttonSource, /hasAttribute\('href'\)/, 'buttons must support navigation without app-specific styling');
assert.match(buttonSource, /getAttribute\('icon'\)/);
assert.match(buttonSource, /getAttribute\('text'\)/);
assert.doesNotMatch(buttonSource, /hasAttribute\('icon-only'\)/);
const componentStyles = await readFile('src/styles.css', 'utf8');
assert.match(componentStyles, /\.se-button--link \{[^}]*color: var\(--se-primary\)/, 'link buttons must use the brand color');
assert.match(componentStyles, /se-sidebar-button:not\(\[active\]\) \.se-sidebar-button:hover/, 'active sidebar buttons must ignore hover styling');
assert.match(componentStyles, /\[data-theme="dark"\] \.se-select__option\[aria-selected="true"\][^{]*\{ color: color-mix\(in srgb, white 90%, var\(--se-primary\)\)/, 'dark selected options need brand-tinted near-white text');
assert.match(componentStyles, /\[data-theme="dark"\] \.se-select__option:not\(\[aria-selected="true"\]\):not\(:disabled\):hover \{ color: var\(--se-text\); background: var\(--se-surface-soft\)/, 'dark option hover must match sidebar hover');
assert.match(componentStyles, /\[data-theme="dark"\] se-sidebar-button\[active\] \.se-sidebar-button[^{}]*\{ color: color-mix\(in srgb, white 90%, var\(--se-primary\)\)/, 'dark active sidebar buttons need brand-tinted near-white text');
assert.match(componentStyles, /\.se-button--link:hover \{[^}]*text-decoration: underline/, 'link buttons must underline on hover');
assert.match(componentStyles, /\.se-button \{[^}]*width: 100%/, 'buttons must fill stretched hosts');
assert.match(componentStyles, /\.se-profile strong, \.se-profile small \{[^}]*text-overflow: ellipsis/, 'profile text must truncate in narrow containers');
assert.match(componentStyles, /se-profile \{[^}]*max-width: 100%/, 'profiles must stay within their container');
assert.match(componentStyles, /\[data-sidebar-collapsed\] \.se-profile > span:nth-child\(2\)/, 'collapsed sidebars must hide profile identity text');
assert.match(componentStyles, /\[data-popover-y="up"\]/, 'menus must support adaptive vertical placement');
assert.match(await readFile('src/helpers.js', 'utf8'), /export const placePopover/, 'menus must share viewport-aware placement');
globalThis.innerWidth = 500;
globalThis.innerHeight = 500;
const testPopover = { dataset: {}, getBoundingClientRect: () => ({ width: 200, height: 200 }) };
placePopover({ getBoundingClientRect: () => ({ top: 10, right: 50, bottom: 50, left: 10 }) }, testPopover);
assert.deepEqual(testPopover.dataset, { popoverY: 'down', popoverX: 'right' });
placePopover({ getBoundingClientRect: () => ({ top: 450, right: 490, bottom: 490, left: 450 }) }, testPopover);
assert.deepEqual(testPopover.dataset, { popoverY: 'up', popoverX: 'left' });
assert.match(componentStyles, /width: var\(--se-sidebar-width, 16rem\)/, 'sidebar width must remain configurable');
const sidebarGroupSource = await readFile('src/components/sidebar-group.js', 'utf8');
assert.match(sidebarGroupSource, /getAttribute\('variant'\) === 'page'/);
assert.match(sidebarGroupSource, /setTimeout\(\(\) => \{ this\.collapsed = false; \}, 200\)/);
assert.doesNotMatch(sidebarGroupSource, /variant.*recent/);
const modalSource = await readFile('src/components/modal.js', 'utf8');
assert.match(modalSource, /<se-empty-state/);
assert.doesNotMatch(modalSource, /hasAttribute\('centered'\)/);
const badgeSource = await readFile('src/components/badge.js', 'utf8');
assert.match(badgeSource, /getAttribute\('icon'\)/);
assert.match(badgeSource, /getAttribute\('text'\)/);
const iconSource = await readFile('src/components/icon.js', 'utf8');
assert.match(iconSource, /from 'lucide'/);
assert.doesNotMatch(iconSource, /<path|<circle|<rect/);
Object.entries(iconNames).forEach(([name, lucideName]) => assert.ok(lucideIcons[lucideName] || extraIcons[lucideName], `${name} must map to a real Lucide icon`));
const phoneSource = await readFile('src/components/phone-input.js', 'utf8');
assert.equal((phoneSource.match(/[A-Z]{2}\|[^;`]+\|\d+/g) || []).length, 245, 'expected complete phone country data');
assert.match(phoneSource, /No countries found\./);
assert.equal(spawnSync(process.execPath, ['--check', 'examples/example.js']).status, 0);
assert.ok(components.length >= 33, 'expected the complete component set');
assert.equal(examplePages.length, 1, 'expected one example HTML page');
for (const file of examplePages) assert.match(await readFile(`examples/${file}`, 'utf8'), /data-demo=/);
const exampleScript = await readFile('examples/example.js', 'utf8');
assert.doesNotMatch(exampleScript, /const demos\s*=/, 'demo markup belongs in HTML');
assert.match(exampleScript, /tag === 'page-layout'[\s\S]*document\.createElement\('iframe'\)/, 'page layout patterns must render in isolated desktop iframes');
assert.match(exampleScript, /new ResizeObserver\(resizeFrame\)/, 'desktop pattern frames must scale with their preview cards');
assert.match(exampleScript, /1024x576[\s\S]*768x1024[\s\S]*390x844/, 'page layout patterns need shared desktop, tablet, and phone viewports');
assert.match(exampleScript, /api\.github\.com\/repos\/DirkDoes\/simple-elements\/tags\?per_page=1/, 'sidebar version must follow the latest GitHub tag');
assert.doesNotMatch(exampleScript, /data-pattern-viewport[^>]*size=/, 'the viewport selector must use the standard select size');
const exampleHtml = await readFile('examples/index.html', 'utf8');
const exampleStyles = await readFile('examples/example.css', 'utf8');
assert.match(exampleStyles, /\.demo-template-table \.se-list__row > :is\(se-input, se-select, se-checkbox, se-code-editor\) \{ overflow: visible; \}/, 'attribute-table selects must override cell menu clipping');
assert.match(exampleStyles, /\.demo-template-table \.se-list__header \{ border-radius: \.75rem \.75rem 0 0; \}/, 'visible table overflow must preserve rounded headers');
assert.equal((exampleHtml.match(/<section data-demo=/g) || []).length, 2, 'dashboard and custom input pages should remain in static HTML');
assert.match(exampleHtml, /data-demo="dashboard"/);
assert.match(exampleHtml, /<small class="demo-version" aria-label="Latest released version"><\/small>/, 'sidebar version must not be hardcoded');
assert.match(exampleHtml, /<se-badge tone="brand" icon="zap" text="Framework-free UI building blocks">/, 'dashboard hero badge must use the brand tone');
assert.match(exampleHtml, /<se-drawer id="dashboard-chat" mode="overlay-clear" width="30rem"/);
assert.match(exampleHtml, /data-open="dashboard-chat"/);
assert.match(exampleHtml, /label="Owners" name="workspace\[owners\]" value="you" multiple searchable[^>]*"locked":true/, 'dashboard workspace form needs locked multi-owner selection');
assert.ok((exampleHtml.match(/<se-chat-message/g) || []).length >= 10, 'dashboard drawer should demonstrate scrolling chat history');
assert.match(exampleHtml, /data-demo="template"/);
assert.equal((exampleHtml.match(/data-template-attribute=/g) || []).length, 11, 'expected every relevant input attribute in the template');
assert.match(exampleScript, /template\.querySelector\('\[data-template-preview\]'\)\.innerHTML = markup/);
assert.match(exampleScript, /closest\('se-input\[data-template-attribute\]'\)/, 'text overrides should render on input');
assert.match(exampleScript, /!control\.matches\('se-input'\)/, 'switches and selects should render only once on change');
assert.match(exampleScript, /customElements\.get\('se-input'\)\.defaultsFor\(type\)/);
assert.doesNotMatch(exampleScript, /inputTypeDefaults/);
const rangeSource = await readFile('src/components/range.js', 'utf8');
assert.match(rangeSource, /Math\.max\(2, Number\.parseInt/);
assert.match(rangeSource, /hasAttribute\('fill'\)/);
assert.match(rangeSource, /JSON\.parse/);
assert.doesNotMatch(rangeSource, /getAttribute\('step'\)/);
assert.match(rangeSource, /Number\(current\.toFixed\(decimals\)\)/);
assert.match(rangeSource, /Math\.round\(\(clamp\(value\) - min\) \/ step\)/);
assert.match(rangeSource, /<span style="left:\$\{index \/ \(steps - 1\) \* 100\}%">\$\{escapeHtml\(label\)\}<\/span>/);
assert.match(exampleHtml, /<se-code-editor data-template-code language="html" readonly wrap hidden>/);
assert.doesNotMatch(exampleHtml, /data-template-wrap-toggle/);
const colorPickerSource = await readFile('src/components/color-picker.js', 'utf8');
assert.match(colorPickerSource, /export const colorPalette/);
const baseColorPalette = colorPickerSource.match(/export const colorPalette = \[(.*?)\];/)?.[1] || '';
assert.equal((baseColorPalette.match(/#[\da-f]{6}/gi) || []).length, 16, 'color picker palette should contain 16 colors');
assert.match(colorPickerSource, /data-gradient/);
assert.match(colorPickerSource, /data-color/);
assert.match(colorPickerSource, /data-swatch/);
assert.match(colorPickerSource, /getAttribute\('mode'\)/);
assert.match(colorPickerSource, /getAttribute\('size'\)/);
assert.match(colorPickerSource, /8:|16:|32:/);
assert.doesNotMatch(colorPickerSource, /hasAttribute\('popover'\)/);
const documentedComponents = components;
assert.equal(componentCatalog.length, documentedComponents.length, 'every standalone component needs a catalog page');
assert.deepEqual(new Set(componentCatalog.map(({ tag }) => `${tag}.js`)), new Set(documentedComponents), 'catalog tags must match standalone component files');
assert.deepEqual(patternCatalog.map(({ tag }) => tag), ['comments', 'multi-scope-navigation', 'workspaces', 'page-layout', 'chats', 'file-system', 'forms'], 'all patterns must be documented');
assert.ok(patternCatalog.every(({ examples }) => examples?.length), 'each pattern needs named examples');
assert.ok(patternCatalog.find(({ tag }) => tag === 'page-layout').examples.every(({ markup }) => markup.includes('layout-mode="responsive"')), 'every page layout pattern needs responsive navigation');
assert.ok(patternCatalog.find(({ tag }) => tag === 'page-layout').examples.slice(0, 3).every(({ markup }) => markup.includes('<se-topbar layout-mode="mobile-only">')), 'sidebar-only layouts need a mobile top bar');
assert.ok(patternCatalog.find(({ tag }) => tag === 'page-layout').examples.slice(1, 3).every(({ markup }) => markup.includes('<footer layout-mode="desktop-only">')), 'mobile top-bar profiles must not be duplicated in sidebar footers');
assert.match(patternCatalog.find(({ tag }) => tag === 'page-layout').examples[2].markup, /<header layout-mode="desktop-only">/, 'the mobile top-bar brand must not be duplicated in the sidebar header');
assert.match(patternCatalog.find(({ tag }) => tag === 'page-layout').examples[3].markup, /<se-sidebar id="windowed-sidebar" layout-mode="responsive" overlay closed>/, 'the hamburger sidebar pattern must demonstrate overlay mode');
assert.equal(patternCatalog.find(({ tag }) => tag === 'page-layout').examples.filter(({ markup }) => /<se-sidebar[^>]* overlay(?: |>|$)/.test(markup)).length, 1, 'only the responsive top-bar pattern should use an overlay sidebar');
const formExamples = patternCatalog.find(({ tag }) => tag === 'forms').examples;
assert.equal(formExamples.length, 4, 'forms pattern must show four workflows');
assert.match(formExamples.find(({ title }) => title === 'New project').markup, /label="Owners" name="owners" value="you" multiple searchable[^>]*"locked":true/, 'project form needs locked multi-owner selection');
assert.equal(formExamples.filter(({ markup }) => markup.includes('<se-split-button')).length, 2, 'two form patterns must use split buttons');
for (const tag of ['checkbox', 'code-editor', 'color-picker', 'date-picker', 'datetime-picker', 'file-upload', 'input', 'phone-input', 'radio', 'range', 'select', 'theme-switch', 'time-picker', 'wysiwyg']) assert.ok(formExamples.some(({ markup }) => markup.includes(`<se-${tag}`)), `forms pattern must demonstrate se-${tag}`);
for (const tag of ['sidebar', 'sidebar-toggle', 'topbar']) {
  const mode = componentCatalog.find((component) => component.tag === tag).attributes.find((attribute) => attribute.name === 'layout-mode');
  assert.equal(mode.defaultValue, 'always', `${tag} layout mode must default to always`);
  assert.equal(mode.options[0], 'always', `${tag} layout mode must list always first`);
}
assert.equal(new Set(componentCatalog.map(({ tag }) => tag)).size, componentCatalog.length, 'catalog pages must be unique');
componentCatalog.forEach(({ tag, icon, attributes, custom }) => {
  assert.ok(iconNames[icon], `${tag} needs a supported sidebar icon`);
  assert.ok(custom || attributes.length, `${tag} needs editable attributes`);
});
for (const { tag, attributes, custom } of componentCatalog) {
  if (custom) continue;
  const source = await readFile(`src/components/${tag}.js`, 'utf8');
  const documentation = await readFile(`docs/${tag}.md`, 'utf8');
  const used = [...source.matchAll(/this\.(?:get|has)Attribute\('([^']+)'\)/g)].map((match) => match[1]).filter((name) => name !== 'id' && !name.startsWith('data-'));
  const listed = new Set(attributes.map(({ name }) => name));
  used.forEach((name) => assert.ok(listed.has(name), `${tag} catalog is missing ${name}`));
  attributes.filter(({ name }) => !['content', 'child-content'].includes(name)).forEach(({ name }) => assert.ok(documentation.includes(`\`${name}`) || documentation.includes(` ${name}=`) || documentation.includes(` ${name} `), `${tag} docs are missing ${name}`));
}
assert.match(exampleScript, /querySelectorAll\('\.demo-component-attributes \[data-component-attribute\], \.demo-component-attributes \[data-component-context\]'\)/, 'attribute and context controls may rebuild a preview');
assert.match(exampleScript, /const sourceTemplate = document\.createElement\('template'\)/, 'overrides must rebuild one-shot components');
assert.match(await readFile('src/components/code-editor.js', 'utf8'), /<textarea name=/, 'code editor must submit through a native textarea');
assert.match(await readFile('src/components/code-editor.js', 'utf8'), /hasAttribute\('readonly'\)/, 'code editor must support readonly');
const drawerSource = await readFile('src/components/drawer.js', 'utf8');
assert.match(drawerSource, /mode === 'overlay' && event\.target === event\.currentTarget/);
assert.match(drawerSource, /aria-modal="\$\{mode === 'overlay'\}"/);
assert.match(drawerSource, /const content = \[\.\.\.this\.childNodes\]/);
assert.match(drawerSource, /querySelector\('\.se-drawer__body'\)\.append\(\.\.\.content\)/);
const toastSource = await readFile('src/components/toast.js', 'utf8');
assert.match(toastSource, /setTimeout\(\(\) => this\.close\(\), duration\)/);
assert.match(toastSource, /data-action/);
assert.match(toastSource, /querySelectorAll\('se-toast\[open\]'\)/, 'open toasts must be stacked');
assert.match(toastSource, /index === toasts\.length - 1/, 'only the bottom toast may cast a stack shadow');
assert.match(await readFile('src/styles.css', 'utf8'), /se-toast \{[^}]*z-index: 1000/, 'toasts must remain above application shells');
assert.doesNotMatch(componentStyles, /\[data-theme="dark"\] \.se-toast--error/, 'dark-mode toasts must use shared dark status tokens');
assert.match(exampleScript, /if \(tag !== 'toast'\)/, 'the toast demo must create a new toast per click');
const splitButtonSource = await readFile('src/components/split-button.js', 'utf8');
assert.match(splitButtonSource, /hasAttribute\('direct'\)/, 'split buttons must support immediate menu actions');
assert.match(splitButtonSource, /se-button--\$\{escapeHtml\(variant\)\}/, 'split buttons must share button variants');
assert.match(await readFile('src/styles.css', 'utf8'), /\.se-split:focus-within/, 'split-button focus must surround the complete control');
assert.match(await readFile('src/styles.css', 'utf8'), /\.se-split--primary > \.se-button:first-child[^}]*255 255 255/, 'primary split buttons need a light divider');
const themeSwitchSource = await readFile('src/components/theme-switch.js', 'utf8');
assert.match(themeSwitchSource, /\['light', 'system', 'dark'\]/, 'ternary theme switches must include system preference');
assert.match(themeSwitchSource, /type="hidden"/, 'button theme switches must submit their string value');
assert.match(themeSwitchSource, /variant === 'button' \|\| variant === 'switch'/, 'switch presentation must use one cycling button');
assert.match(themeSwitchSource, /<se-segmented-control/, 'segmented theme switches must reuse the shared control');
const segmentedControlSource = await readFile('src/components/segmented-control.js', 'utf8');
assert.match(segmentedControlSource, /_groupName/, 'unnamed segmented controls must remain one radio group');
assert.match(await readFile('src/styles.css', 'utf8'), /--se-segment-index[^}]*transition: transform/, 'segmented selection must animate between options');
assert.match(await readFile('src/components/card.js', 'utf8'), /CSS\.supports\('color', color\)/, 'custom card colors must be validated');
assert.match(await readFile('src/components/list-row.js', 'utf8'), /--se-list-row-indent/, 'list rows must expose table-tree indentation');
assert.match(componentStyles, /\.se-table \.se-list__header, \.se-table \.se-list__row \{[^}]*grid-template-columns: subgrid/, 'table headers and rows must share the scrolling column grid');
assert.match(await readFile('src/components/collection.js', 'utf8'), /--se-mobile-columns/, 'tables must support compact mobile columns');
assert.match(componentStyles, /\.se-table \.se-list__header > \*, \.se-table \.se-list__row > \* \{[^}]*text-overflow: ellipsis/, 'table cells must truncate overflow');
assert.match(componentStyles, /\.se-table \.se-list__header \[layout-mode="mobile-only"\], \.se-table \.se-list__row \[layout-mode="mobile-only"\] \{ display: none; \}/, 'mobile-only table content must stay hidden on desktop');
assert.doesNotMatch(componentStyles, /\[layout-mode="mobile-only"\] \{ display: revert !important; \}/, 'responsive visibility must not override component layout displays');
const treeItemSource = await readFile('src/components/tree-item.js', 'utf8');
assert.match(treeItemSource, /<details/, 'folders must use native disclosure behavior');
assert.doesNotMatch(treeItemSource, /role="treeitem"/, 'native disclosure items must not claim full tree-widget behavior');
assert.match(await readFile('src/components/wysiwyg.js', 'utf8'), /<textarea hidden name=/, 'WYSIWYG must submit through a native textarea');
const wysiwygSource = await readFile('src/components/wysiwyg.js', 'utf8');
assert.match(wysiwygSource, /<se-select data-format size="small" value="markdown"/);
assert.doesNotMatch(wysiwygSource, /<select data-format/);
assert.match(wysiwygSource, /<button type="button" data-source-toggle/);
assert.doesNotMatch(wysiwygSource, /<se-button data-source-toggle/);
assert.match(wysiwygSource, /highlightCode\(source\.value, this\._format\)/);
assert.match(wysiwygSource, /editor\.innerHTML = this\._html/);
assert.match(wysiwygSource, /if \(!this\._sourceVisible\) this\._html = editor\.innerHTML/);
assert.doesNotMatch(wysiwygSource, /this\._sourceVisible \? \(this\._format/);
assert.match(wysiwygSource, /source\.setRangeText/);
assert.match(wysiwygSource, /\{ b: 'bold', i: 'italic' \}/);
assert.match(wysiwygSource, /items\.join\(''\)/, 'WYSIWYG must group adjacent Markdown list items into one list');
const exampleSource = await readFile('examples/example.js', 'utf8');
assert.match(exampleSource, /attributes\.forEach\(\(\{ name \}\) =>/);
const chatMessageSource = await readFile('src/components/chat-message.js', 'utf8');
assert.match(chatMessageSource, /const avatar = initials \?/);
assert.match(await readFile('src/components/chat-context.js', 'utf8'), /se-chat-context--\$\{variant\}/);
assert.match(await readFile('src/components/thought-train.js', 'utf8'), /se-thought-train--\$\{variant\}/);
const topbarSource = await readFile('src/components/topbar.js', 'utf8');
assert.match(topbarSource, /data-mobile-search/, 'top bar must manage its mobile search row');
assert.match(topbarSource, /closedchange/, 'top bar overlays must close each other');
assert.match(await readFile('src/components/sidebar.js', 'utf8'), /data-transitioning/, 'sidebar animation must suppress temporary scrollbars');
assert.match(await readFile('src/styles.css', 'utf8'), /se-sidebar\[overlay\]\[closed\]\[data-transitioning\]/, 'closing overlay sidebars must stay visible for their transition');
assert.doesNotMatch(await readFile('src/components/sidebar.js', 'utf8'), /data-overlay-transitioning/, 'overlay positioning must not depend on collapse transitions');
assert.match(highlightCode('const ready = true;', 'javascript'), /se-token--keyword/);
const highlightedHtml = highlightCode('<se-button variant="brand" text="Save" disabled></se-button>', 'html');
assert.match(highlightedHtml, /se-token--tag[^>]*>&lt;se-button/);
assert.match(highlightedHtml, /se-token--property[^>]*>variant/);
assert.match(highlightedHtml, /se-token--operator[^>]*>=/);
assert.match(highlightedHtml, /se-token--string[^>]*>&quot;brand&quot;/);
assert.match(highlightedHtml, /se-token--property[^>]*>disabled/);
assert.match(renderMarkdown('> Safe\n\n```json\n{"ready":true}\n```'), /<se-blockquote>Safe<\/se-blockquote>.*<se-code block language="json">/s);
assert.doesNotMatch(renderMarkdown('<script>alert(1)</script>'), /<script>/);
assert.equal(dateValue(parseDate('2026-09-06')), '2026-09-06');
assert.equal(parseDate('2026-02-30'), null);
assert.equal(calendarDays(2026, 8).length, 42);
assert.deepEqual(parseTime('09:30'), { hour: 9, minute: 30 });
assert.equal(parseTime('25:00'), null);
assert.equal(timeValue({ hour: 9, minute: 5 }), '09:05');
assert.equal(wrapNumber(24, 24), 0);
assert.equal(wrapNumber(-5, 60), 55);
assert.match(await readFile('src/components/collection.js', 'utf8'), /--se-columns/);
const datetimeSource = await readFile('src/components/datetime-picker.js', 'utf8');
assert.match(datetimeSource, /variant === 'combined'/);
assert.match(datetimeSource, /:scope > \.se-datetime-single > input, :scope > fieldset > input/, 'default combined picker must resolve its hidden form input');
console.log(`Checked ${components.length} components, ${componentCatalog.length} component pages, and ${patternCatalog.length} pattern page.`);

const flatCss = await readFile('src/themes/flat.css', 'utf8');
assert.equal(await readFile('dist/themes/flat.css', 'utf8'), flatCss, 'the optional Flat stylesheet must be built');
assert.match(compiledCss, /:root:not\(\[data-se-theme="clean"\], \[data-se-theme="studio"\], \[data-se-theme="edge"\]\)/, 'Flat must apply when no theme is selected');
assert.doesNotMatch(await readFile('dist/themes/clean.css', 'utf8'), /data-se-theme/, 'Clean-only apps must not bundle Flat');
assert.doesNotMatch(await readFile('dist/simple-elements.js', 'utf8'), /se-flat|themes\/flat/, 'theme CSS must not be embedded in component JavaScript');
assert.equal(JSON.parse(await readFile('package.json', 'utf8')).exports['./themes/flat.css'], './dist/themes/flat.css');
assert.match(flatCss, /--se-shadow: none/);
assert.match(flatCss, /--se-shadow-lg: none/);
assert.match(flatCss, /border-bottom-color: var\(--se-border-strong\)/, 'flat fields must retain a visible control boundary');
assert.match(flatCss, /:focus-visible/, 'flat controls must retain keyboard focus');
const showcaseShell = await readFile('examples/pages/shell.html', 'utf8');
assert.ok(showcaseShell.length < exampleHtml.length / 2, 'the entry template should stay small');
for (const page of ['dashboard', 'input']) assert.ok(exampleHtml.includes((await readFile(`examples/pages/${page}.html`, 'utf8')).trim()), `${page} must be assembled into the deployed showcase`);
assert.doesNotMatch(exampleHtml, /<!-- page:/, 'all page includes must be resolved at build time');
assert.match(exampleHtml, /class="demo-theme-family"[^>]*"label":"Flat"[^>]*"label":"Clean"/);

const studioCss = await readFile('src/themes/studio.css', 'utf8');
assert.equal(await readFile('dist/themes/studio.css', 'utf8'), studioCss);
assert.doesNotMatch(compiledCss, /:root\[data-se-theme="studio"\]/, 'Studio must remain an optional stylesheet');
assert.equal(JSON.parse(await readFile('package.json', 'utf8')).exports['./themes/studio.css'], './dist/themes/studio.css');
assert.match(exampleHtml, /"label":"Studio"/);

assert.equal(await readFile('dist/themes/edge.css', 'utf8'), await readFile('src/themes/edge.css', 'utf8'));
assert.doesNotMatch(compiledCss, /:root\[data-se-theme="edge"\]/, 'Edge must remain optional');

for (const name of ["unlink", "external-link", "qr-code", "star", "house", "circle-check", "map-pin", "sparkles", "pencil", "circle-x", "calendar", "log-out", "download", "arrow-left", "arrow-up", "arrow-down", "arrow-right", "save", "camera", "rocket", "truck", "languages", "box", "map", "paperclip", "database", "notebook-pen", "message-square", "messages-square", "grip-vertical", "car", "blocks", "pin", "palette", "timer", "receipt-text", "crown", "scroll-text", "book-open-text", "thumbs-up", "audio-lines", "leaf", "network", "boxes", "list-checks", "plane", "folder-open", "ticket", "images", "files", "inbox", "scan", "type", "laptop", "locate", "lock", "lock-open", "scan-qr-code", "archive", "ruler", "square-terminal", "thumbs-down", "skip-forward", "play", "pause", "trash", "trash-off", "rotate-ccw", "book-plus", "share-2", "star-off", "play-off"]) assert.ok(iconNames[name], `Requested icon ${name} must be bundled`);
