import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { highlightCode, renderMarkdown } from '../src/syntax.js';
import { calendarDays, dateValue, parseDate, parseTime, timeValue, wrapNumber } from '../src/calendar.js';
import { iconNames } from '../src/icon-names.js';
import { componentCatalog } from '../examples/catalog.js';
import { icons as lucideIcons } from 'lucide';

const components = (await readdir('src/components')).filter((file) => file.endsWith('.js'));
const examplePages = (await readdir('examples')).filter((file) => file.endsWith('.html'));
const entry = await readFile('src/index.js', 'utf8');

for (const file of components) {
  assert.match(entry, new RegExp(`components/${file.replace('.', '\\.')}`), `${file} is not exported`);
  await readFile(`docs/${file.replace('.js', '.md')}`, 'utf8');
  const check = spawnSync(process.execPath, ['--check', `src/components/${file}`], { encoding: 'utf8' });
  assert.equal(check.status, 0, check.stderr);
}

assert.equal(spawnSync(process.execPath, ['--check', 'src/index.js']).status, 0);
assert.equal(spawnSync(process.execPath, ['--check', 'dist/simple-elements.js']).status, 0);
assert.match(await readFile('dist/simple-elements.js', 'utf8'), /const connectChoice =/, 'shared choice renderer must be included in the browser bundle');
const compiledCss = await readFile('dist/styles.css', 'utf8');
assert.match(compiledCss, /\.se-button/);
assert.match(compiledCss, /\[hidden\]/);
assert.match(compiledCss, /\.se-choice--switch/);
assert.match(compiledCss, /textarea:read-only\{[^}]*resize:none/);
assert.match(compiledCss, /se-code\[block\]\[wrap\]/);
assert.match(compiledCss, /se-code-editor\[wrap\]/);
assert.doesNotMatch(compiledCss, /@import\s/);
const selectSource = await readFile('src/components/select.js', 'utf8');
assert.match(selectSource, /const trigger = multiple/);
assert.match(selectSource, /option\.icon/);
assert.match(selectSource, /set value\(value\)/);
assert.match(selectSource, /hasAttribute\('clearable'\)/);
assert.match(selectSource, /const clearable = !multiple/);
assert.match(selectSource, /this\._selected\.clear\(\)/);
const inputSource = await readFile('src/components/input.js', 'utf8');
assert.match(inputSource, /email: \{ placeholder: 'you@example\.com', icon: 'mail' \}/);
assert.match(inputSource, /tel: \{ placeholder: 'Enter a phone number\.\.\.', icon: 'phone' \}/);
assert.match(inputSource, /static defaultsFor\(type = 'text'\)/);
const buttonSource = await readFile('src/components/button.js', 'utf8');
assert.match(buttonSource, /getAttribute\('icon'\)/);
assert.match(buttonSource, /getAttribute\('text'\)/);
assert.doesNotMatch(buttonSource, /hasAttribute\('icon-only'\)/);
const badgeSource = await readFile('src/components/badge.js', 'utf8');
assert.match(badgeSource, /getAttribute\('icon'\)/);
assert.match(badgeSource, /getAttribute\('text'\)/);
const iconSource = await readFile('src/components/icon.js', 'utf8');
assert.match(iconSource, /from 'lucide'/);
assert.doesNotMatch(iconSource, /<path|<circle|<rect/);
Object.entries(iconNames).forEach(([name, lucideName]) => assert.ok(lucideIcons[lucideName], `${name} must map to a real Lucide icon`));
const phoneSource = await readFile('src/components/phone-input.js', 'utf8');
assert.equal((phoneSource.match(/[A-Z]{2}\|[^;`]+\|\d+/g) || []).length, 245, 'expected complete phone country data');
assert.match(phoneSource, /No countries found\./);
assert.equal(spawnSync(process.execPath, ['--check', 'examples/example.js']).status, 0);
assert.ok(components.length >= 33, 'expected the complete component set');
assert.equal(examplePages.length, 1, 'expected one example HTML page');
for (const file of examplePages) assert.match(await readFile(`examples/${file}`, 'utf8'), /data-demo=/);
const exampleScript = await readFile('examples/example.js', 'utf8');
assert.doesNotMatch(exampleScript, /const demos\s*=/, 'demo markup belongs in HTML');
const exampleHtml = await readFile('examples/index.html', 'utf8');
assert.equal((exampleHtml.match(/<section data-demo=/g) || []).length, 1, 'only the custom input page should remain in static HTML');
assert.match(exampleHtml, /data-demo="template"/);
assert.equal((exampleHtml.match(/data-template-attribute=/g) || []).length, 11, 'expected every relevant input attribute in the template');
assert.match(exampleScript, /template\.querySelector\('\[data-template-preview\]'\)\.innerHTML = markup/);
assert.match(exampleScript, /closest\('se-input\[data-template-attribute\]'\)/, 'text overrides should render on input');
assert.match(exampleScript, /!control\.matches\('se-input'\)/, 'switches and selects should render only once on change');
assert.match(exampleScript, /customElements\.get\('se-input'\)\.defaultsFor\(type\)/);
assert.doesNotMatch(exampleScript, /inputTypeDefaults/);
assert.match(exampleHtml, /<se-code-editor data-template-code language="html" readonly wrap hidden>/);
assert.doesNotMatch(exampleHtml, /data-template-wrap-toggle/);
assert.equal(componentCatalog.length, components.length, 'every component needs a catalog page');
assert.deepEqual(new Set(componentCatalog.map(({ tag }) => `${tag}.js`)), new Set(components), 'catalog tags must match component files');
assert.equal(new Set(componentCatalog.map(({ tag }) => tag)).size, componentCatalog.length, 'catalog pages must be unique');
componentCatalog.forEach(({ tag, icon, attributes, custom }) => {
  assert.ok(iconNames[icon], `${tag} needs a supported sidebar icon`);
  assert.ok(custom || attributes.length, `${tag} needs editable attributes`);
});
for (const { tag, attributes, custom } of componentCatalog) {
  if (custom) continue;
  const source = await readFile(`src/components/${tag}.js`, 'utf8');
  const used = [...source.matchAll(/(?:get|has)Attribute\('([^']+)'\)/g)].map((match) => match[1]).filter((name) => name !== 'id' && !name.startsWith('data-'));
  const listed = new Set(attributes.map(({ name }) => name));
  used.forEach((name) => assert.ok(listed.has(name), `${tag} catalog is missing ${name}`));
}
assert.match(exampleScript, /closest\('\.demo-component-attributes \[data-component-attribute\]'\)/, 'only attribute controls may rebuild a preview');
assert.match(exampleScript, /const sourceTemplate = document\.createElement\('template'\)/, 'overrides must rebuild one-shot components');
assert.match(await readFile('src/components/code-editor.js', 'utf8'), /<textarea name=/, 'code editor must submit through a native textarea');
assert.match(await readFile('src/components/code-editor.js', 'utf8'), /hasAttribute\('readonly'\)/, 'code editor must support readonly');
assert.match(await readFile('src/components/wysiwyg.js', 'utf8'), /<textarea hidden name=/, 'WYSIWYG must submit through a native textarea');
assert.match(highlightCode('const ready = true;', 'javascript'), /se-token--keyword/);
const highlightedHtml = highlightCode('<se-button variant="brand" text="Save" disabled></se-button>', 'html');
assert.match(highlightedHtml, /se-token--tag[^>]*>&lt;se-button/);
assert.match(highlightedHtml, /se-token--property[^>]*>variant/);
assert.match(highlightedHtml, /se-token--operator[^>]*>=/);
assert.match(highlightedHtml, /se-token--string[^>]*>&quot;brand&quot;/);
assert.match(highlightedHtml, /se-token--property[^>]*>disabled/);
assert.match(renderMarkdown('> Safe\n\n```json\n{"ready":true}\n```'), /<se-blockquote>Safe<\/se-blockquote>.*<se-code block language="json">/s);
assert.doesNotMatch(renderMarkdown('<script>alert(1)</script>'), /<script>/);
assert.equal(dateValue(parseDate('2026-09-06')), '2026-09-06');
assert.equal(parseDate('2026-02-30'), null);
assert.equal(calendarDays(2026, 8).length, 42);
assert.deepEqual(parseTime('09:30'), { hour: 9, minute: 30 });
assert.equal(parseTime('25:00'), null);
assert.equal(timeValue({ hour: 9, minute: 5 }), '09:05');
assert.equal(wrapNumber(24, 24), 0);
assert.equal(wrapNumber(-5, 60), 55);
assert.match(await readFile('src/components/table.js', 'utf8'), /--se-columns/);
const datetimeSource = await readFile('src/components/datetime-picker.js', 'utf8');
assert.match(datetimeSource, /variant === 'combined'/);
assert.match(datetimeSource, /:scope > \.se-datetime-single > input, :scope > fieldset > input/, 'default combined picker must resolve its hidden form input');
console.log(`Checked ${components.length} components and ${componentCatalog.length} catalog pages.`);
