const a = (name, description, defaultValue = '', control = 'text', options = []) => ({ name, description, defaultValue, control, options });
const variants = ['gray', 'brand', 'success', 'warning', 'error', 'info', 'important'];
const languages = ['javascript', 'json', 'markdown', 'html', 'css', 'python'];
const icons = ['activity', 'alert', 'bell', 'bold', 'calendar', 'check', 'chevron', 'clock', 'code', 'copy', 'crown', 'dashboard', 'database', 'edit', 'eye', 'eye-off', 'file', 'file-up', 'info', 'italic', 'link', 'list', 'list-ordered', 'lock', 'mail', 'menu', 'message-square', 'moon', 'more', 'mouse-pointer', 'package', 'palette', 'panel-left-close', 'panel-left-open', 'phone', 'search', 'send', 'settings', 'shield-alert', 'sun', 'table', 'toggle-left', 'trash', 'type', 'underline', 'upload', 'user', 'users', 'x', 'zap'];
icons.push('badge', 'blockquote', 'calendar-clock', 'card', 'checkbox', 'folder', 'list-header', 'list-row', 'list-start', 'message-help', 'panel-right', 'radio', 'range', 'text-input', 'wysiwyg');
icons.sort();
const sidebarContext = [a('sidebar-collapsed', 'Applies the compact presentation used inside a collapsed sidebar.', 'false', 'boolean')];

const components = [
  { tag: 'badge', icon: 'crown', description: 'Compact status label with optional icon and text.', markup: '<se-badge></se-badge>', attributes: [a('tone', 'Sets the badge color family.', 'gray', 'select', variants), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('text', 'Sets the badge text.', 'Badge'), a('aria-label', 'Labels an icon-only badge for assistive technology.')] },
  { tag: 'blockquote', icon: 'message-square', description: 'Highlighted quotation or callout matching the badge color family.', markup: '<se-blockquote>Simple components compose well.</se-blockquote>', attributes: [a('tone', 'Sets the quotation color family.', 'brand', 'select', variants), a('content', 'Sets the quotation content.', 'Simple components compose well.', 'content')] },
  { tag: 'button', icon: 'mouse-pointer', description: 'Action button that derives icon-only, text-only, or combined layout from its attributes.', markup: '<se-button></se-button>', attributes: [a('variant', 'Sets the visual button style.', 'primary', 'select', ['primary', 'brand', 'secondary', 'ghost', 'danger', 'label']), a('type', 'Sets the native button type.', 'button', 'select', ['button', 'submit', 'reset']), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('text', 'Sets the visible button label.', 'Button'), a('disabled', 'Disables the native button.', 'false', 'boolean'), a('aria-label', 'Overrides the accessible button label.')] },
  { tag: 'card', icon: 'package', description: 'Surface container for grouping related content.', markup: '<se-card><se-title level="card">Card title</se-title><se-text>Card content</se-text></se-card>', attributes: [a('variant', 'Sets the surface treatment.', 'white', 'select', ['white', 'gray', 'transparent']), a('color', 'Sets a CSS background color and overrides variant.'), a('content', 'Sets the HTML inside the card.', '<se-title level="card">Card title</se-title><se-text>Card content</se-text>', 'content')] },
  { tag: 'chat-context', icon: 'info', description: 'Non-message event marker for changes and activity in a conversation.', markup: '<se-chat-context icon="info" timestamp="09:42">Maya pinned the project brief.</se-chat-context>', attributes: [a('variant', 'Sets the marker color family.', 'brand', 'select', variants), a('icon', 'Sets the event icon.', 'info', 'select', icons), a('timestamp', 'Adds an event time.'), a('content', 'Sets the event text.', 'Maya pinned the project brief.', 'content')] },
  { tag: 'chat-message', icon: 'message-square', description: 'Sent or received chat bubble with optional profile, title, HTML content, and timestamp.', markup: '<se-chat-message mode="received" title="Assistant" profile timestamp="09:42">Here is the answer.</se-chat-message>', attributes: [a('mode', 'Selects a sent or received message.', 'received', 'select', ['received', 'sent']), a('profile', 'Shows a profile icon.', 'false', 'boolean'), a('initials', 'Shows initials in the profile picture and takes priority over icon.'), a('icon', 'Sets the profile picture icon.', '', 'select', icons), a('title', 'Sets the message title or sender.', 'Assistant'), a('content', 'Sets the message HTML.', 'Here is the answer.', 'content'), a('timestamp', 'Adds a message time.'), a('timestamp-position', 'Places the timestamp before or after the title.', 'end', 'select', ['start', 'end'])] },
  { tag: 'checkbox', icon: 'check', contexts: sidebarContext, description: 'Native checkbox semantics with checkbox, radio, or switch presentation.', markup: '<se-checkbox label="Checkbox"></se-checkbox>', attributes: [a('variant', 'Changes the visual style without changing checkbox semantics.', 'checkbox', 'select', ['checkbox', 'radio', 'switch']), a('label', 'Sets the visible checkbox label.', 'Checkbox'), a('name', 'Names the native field for form submission.'), a('value', 'Sets the submitted value.', 'on'), a('checked', 'Checks the checkbox initially.', 'false', 'boolean'), a('disabled', 'Disables the checkbox.', 'false', 'boolean')] },
  { tag: 'code-editor', icon: 'code', description: 'Syntax-highlighted textarea with line numbers and form submission.', markup: '<se-code-editor language="javascript" value="const ready = true;"></se-code-editor>', attributes: [a('label', 'Adds a label above the editor.'), a('name', 'Names the backing textarea for form submission.'), a('language', 'Selects the highlighting grammar.', 'javascript', 'select', languages), a('value', 'Sets the editor source.', '', 'code'), a('readonly', 'Prevents editing while retaining selection.', 'false', 'boolean'), a('disabled', 'Disables the editor.', 'false', 'boolean'), a('wrap', 'Wraps long visual lines without adding line numbers.', 'false', 'boolean'), a('autosize', 'Grows and shrinks with the content instead of resizing manually.', 'false', 'boolean')] },
  { tag: 'code', icon: 'code', description: 'Inline or block syntax-highlighted code display.', markup: '<se-code>npm install github:DirkDoes/simple-elements</se-code>', attributes: [a('language', 'Selects the highlighting grammar.', '', 'select', languages), a('block', 'Uses the block code presentation.', 'false', 'boolean'), a('wrap', 'Wraps long block-code lines.', 'false', 'boolean'), a('content', 'Sets the displayed source.', 'npm install github:DirkDoes/simple-elements', 'content')] },
  { tag: 'color-picker', icon: 'palette', description: 'Gradient or fixed-palette color selection with inline and popover presentations.', markup: '<se-color-picker label="Accent" value="#3b82f6"></se-color-picker>', attributes: [a('variant', 'Chooses freeform gradient or the fixed palette.', 'gradient', 'select', ['gradient', 'palette']), a('mode', 'Shows the picker inline or behind a trigger.', 'popover', 'select', ['inline', 'popover']), a('size', 'Chooses the fixed palette tier.', '16', 'select', ['8', '16', '32']), a('label', 'Sets an optional visible field label.'), a('name', 'Names the submitted hidden input.'), a('value', 'Sets the initial hex color.', '#3b82f6'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'date-picker', icon: 'calendar', description: 'Styled calendar picker backed by a named hidden input.', markup: '<se-date-picker></se-date-picker>', attributes: [a('label', 'Sets the field label.', 'Date'), a('name', 'Names the submitted field.'), a('value', 'Sets an ISO date in YYYY-MM-DD format.'), a('min', 'Sets the earliest selectable ISO date.'), a('max', 'Sets the latest selectable ISO date.'), a('locale', 'Controls localized month and date labels.'), a('placeholder', 'Sets the empty trigger text.', 'Choose a date'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'datetime-picker', icon: 'calendar', description: 'Date and time input with combined, separated, and joined flows.', markup: '<se-datetime-picker></se-datetime-picker>', attributes: [a('variant', 'Selects the field and popover layout.', 'combined', 'select', ['combined', 'separated', 'joined']), a('label', 'Sets the field label.', 'Date and time'), a('name', 'Names the submitted field.'), a('value', 'Sets an ISO local date-time value.'), a('min', 'Sets the earliest selectable date-time.'), a('max', 'Sets the latest selectable date-time.'), a('step', 'Sets the time step in seconds.', '300'), a('locale', 'Controls localized date labels.'), a('placeholder', 'Sets the empty combined trigger text.', 'Choose date and time'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'drawer', icon: 'panel-left-open', description: 'Side panel that can overlay, overlay without blur, or push the page.', markup: '<se-drawer title="Drawer"><se-text>Drawer content</se-text></se-drawer>', action: 'open', attributes: [a('mode', 'Controls how the drawer relates to the page.', 'overlay', 'select', ['overlay', 'overlay-clear', 'push']), a('width', 'Sets the panel width.', '24rem'), a('title', 'Sets the drawer heading.', 'Drawer'), a('open', 'Opens the drawer initially.', 'false', 'boolean'), a('content', 'Sets the drawer body HTML.', '<se-text>Drawer content</se-text>', 'content')] },
  { tag: 'toast', icon: 'bell', description: 'Top-screen status message with automatic dismissal and an optional same-tab action.', markup: '<se-toast tone="success" message="Changes saved." action="Undo" href="#details"></se-toast>', action: 'open', attributes: [a('tone', 'Sets the status color and default icon.', 'gray', 'select', variants), a('icon', 'Overrides the status icon.', '', 'select', icons), a('message', 'Sets the notification message.', 'Notification'), a('action', 'Adds an optional action label.', ''), a('href', 'Renders the action as a same-tab link instead of a button.', ''), a('duration', 'Sets the automatic dismissal delay in milliseconds; use 0 to disable it.', '5000'), a('open', 'Shows the toast initially.', 'false', 'boolean')] },
  { tag: 'empty-state', icon: 'package', description: 'Centered empty-result message with optional actions.', markup: '<se-empty-state title="No projects yet" text="Create a project to get started." icon="package"><se-button variant="brand" text="Create project"></se-button></se-empty-state>', attributes: [a('tone', 'Sets the icon color family.', 'gray', 'select', variants), a('icon', 'Sets the empty-state icon.', 'package', 'select', icons), a('title', 'Sets the empty-state title.', 'Nothing here yet'), a('text', 'Sets the supporting message.'), a('content', 'Adds use-case-specific actions or controls.', '<se-button variant="brand" text="Create project"></se-button>', 'content')] },
  { tag: 'file-card', icon: 'file', description: 'File summary card with customizable icon, subtext, and actions.', markup: '<se-file-card filename="report.pdf" subtext="2.4 MB"></se-file-card>', attributes: [a('tone', 'Sets the icon color family.', 'brand', 'select', variants), a('filename', 'Sets the displayed filename.'), a('subtext', 'Sets supporting text such as size, type, or status.'), a('icon', 'Sets the leading icon.', 'file', 'select', icons), a('action', 'Adds a removal action icon.', '', 'select', ['x', 'trash']), a('clickable', 'Makes the main file area a button.', 'false', 'boolean')] },
  { tag: 'folder-card', icon: 'folder', description: 'Clickable folder summary with its item count.', markup: '<se-folder-card title="Assets" items="24" href="#assets"></se-folder-card>', attributes: [a('tone', 'Sets the icon color family.', 'brand', 'select', variants), a('title', 'Sets the folder title.', 'Folder'), a('items', 'Sets the number of contained items.', '0'), a('icon', 'Sets the folder icon.', 'folder', 'select', icons), a('href', 'Renders the card as a link.'), a('disabled', 'Disables the card button.', 'false', 'boolean')] },
  { tag: 'project-card', icon: 'package', description: 'Clickable project summary with a color or image banner.', markup: '<se-project-card title="Northstar" description="Customer portal redesign" metadata="Updated today" banner-color="#2563eb"></se-project-card>', attributes: [a('title', 'Sets the project title.', 'Project'), a('description', 'Sets the project description.'), a('metadata', 'Adds compact supporting metadata.'), a('icon', 'Sets the banner icon.', 'package', 'select', icons), a('banner-color', 'Sets a CSS banner color.'), a('banner-image', 'Replaces the color and icon with an image URL.'), a('href', 'Renders the card as a link.'), a('disabled', 'Disables the card button.', 'false', 'boolean')] },
  { tag: 'file-upload', icon: 'file-up', description: 'Styled native file input and drag-and-drop target.', markup: '<se-file-upload></se-file-upload>', attributes: [a('label', 'Sets the field label.', 'Dropzone'), a('prompt', 'Sets the main upload prompt.', 'Upload a file'), a('subprompt', 'Sets the secondary prompt.', 'or drag and drop'), a('hint', 'Sets the accepted-file guidance.', 'PNG, JPG, PDF up to 10MB'), a('name', 'Names the native file input.', 'files'), a('multiple', 'Allows multiple files.', 'false', 'boolean'), a('accept', 'Sets the native accepted file types.')] },
  { tag: 'icon', icon: 'zap', description: 'Lucide icon rendered by a stable Simple Elements name.', markup: '<se-icon name="settings"></se-icon>', attributes: [a('name', 'Selects a bundled Lucide icon.', 'alert', 'select', icons)] },
  { tag: 'input', icon: 'type', description: 'Standard input and textarea with type-aware defaults.', custom: true },
  { tag: 'list-header', icon: 'list', description: 'Header row for flexible lists and tables.', markup: '<se-list-header>Recent activity</se-list-header>', attributes: [a('content', 'Sets the header content.', 'Recent activity', 'content')] },
  { tag: 'list-row', icon: 'list', description: 'Flexible row used inside lists and tables.', markup: '<se-list-row><se-icon name="user"></se-icon><span>A user joined</span></se-list-row>', attributes: [a('level', 'Indents the first table cell for hierarchical rows.', '0'), a('guides', 'Draws a tree connector at the current indentation level.', 'false', 'boolean'), a('content', 'Sets the row content.', '<se-icon name="user"></se-icon><span>A user joined</span>', 'content')] },
  { tag: 'collection', icon: 'list', description: 'One wrapper for lists, tables, and disclosure trees.', markup: '<se-collection type="list"><se-list-header>Activity</se-list-header><se-list-row>First item</se-list-row><se-list-row>Second item</se-list-row></se-collection>', attributes: [a('type', 'Chooses list, table, or disclosure-tree behavior.', 'list', 'select', ['list', 'table', 'tree']), a('columns', 'Sets the shared CSS grid columns in table mode.', 'repeat(auto-fit, minmax(8rem, 1fr))'), a('content', 'Sets the rows or tree items.', '<se-list-header>Activity</se-list-header><se-list-row>First item</se-list-row><se-list-row>Second item</se-list-row>', 'content')] },
  { tag: 'markdown', icon: 'type', description: 'Safely renders basic Markdown as Simple Elements content.', markup: '<se-markdown source="# Heading\n\nMarkdown content"></se-markdown>', attributes: [a('source', 'Sets the Markdown source.', '', 'code')] },
  { tag: 'menu', icon: 'menu', description: 'Button-triggered action menu with icons and disabled items.', markup: `<se-menu label="More" options='[{"label":"Edit","icon":"edit"},{"label":"Delete","icon":"trash","danger":true}]'></se-menu>`, attributes: [a('label', 'Sets the trigger label.', 'More'), a('options', 'Sets the menu option array.', '[]', 'code')] },
  { tag: 'modal', icon: 'message-square', description: 'Small, medium, or large dialog overlay with configurable actions and icon color.', markup: '<se-modal title="Confirm action"><se-text>Modal content</se-text></se-modal>', action: 'open', attributes: [a('tone', 'Sets the icon color family.', 'error', 'select', variants), a('size', 'Sets the dialog layout and width.', 'small', 'select', ['small', 'medium', 'large']), a('title', 'Sets the dialog heading.'), a('subtitle', 'Adds supporting header text to medium and large dialogs.'), a('icon', 'Adds an icon beside the title.', '', 'select', icons), a('cancel-label', 'Sets the cancel action text.', 'Cancel'), a('confirm-label', 'Sets the confirm action text.', 'Confirm'), a('confirm-variant', 'Sets the confirm button variant.', 'brand', 'select', ['primary', 'brand', 'secondary', 'ghost', 'danger']), a('open', 'Opens the modal initially.', 'false', 'boolean'), a('content', 'Sets the modal body HTML.', '<se-text>Modal content</se-text>', 'content')] },
  { tag: 'phone-input', icon: 'phone', description: 'International phone input with every country and calling code.', markup: '<se-phone-input></se-phone-input>', attributes: [a('label', 'Sets the field label.', 'Phone Number'), a('name', 'Names the native telephone input.'), a('country', 'Sets the initial ISO country code.', ''), a('code', 'Selects the initial country by calling code.'), a('placeholder', 'Sets the telephone number placeholder.', '6 12345678')] },
  { tag: 'profile', icon: 'user', contexts: sidebarContext, description: 'Avatar initials with a name, subtitle, and optional button or context menu behavior.', markup: '<se-profile name="Sarah Jenkins" subtitle="Administrator" initials="SJ" options=\'[{"label":"Account settings","icon":"settings"},{"label":"Sign out","icon":"x","danger":true}]\'></se-profile>', attributes: [a('tone', 'Sets the avatar color family.', 'brand', 'select', variants), a('name', 'Sets the displayed name.'), a('subtitle', 'Adds supporting profile text.'), a('initials', 'Sets the avatar initials.'), a('clickable', 'Renders the profile as a button when options are absent.', 'false', 'boolean'), a('options', 'Turns the profile into a context menu; it takes priority over clickable.', '[]', 'code'), a('compact', 'Shows only the avatar, independent of sidebar context.', 'false', 'boolean')] },
  { tag: 'radio', icon: 'toggle-left', contexts: sidebarContext, description: 'Native radio semantics with radio, checkbox, or switch presentation.', markup: '<se-radio label="Radio option"></se-radio>', attributes: [a('variant', 'Changes the visual style without changing radio semantics.', 'radio', 'select', ['radio', 'checkbox', 'switch']), a('label', 'Sets the visible radio label.', 'Radio option'), a('name', 'Names the native radio group.'), a('value', 'Sets the submitted value.', 'on'), a('checked', 'Selects the radio initially.', 'false', 'boolean'), a('disabled', 'Disables the radio.', 'false', 'boolean')] },
  { tag: 'range', icon: 'activity', description: 'Styled range input with optional fill, steps, and labels.', markup: '<se-range label="Volume" value="50" suffix="%" fill steps="5" labels=\'["0%","25%","50%","75%","100%"]\'></se-range>', attributes: [a('label', 'Sets the field label.', 'Range'), a('name', 'Names the native range input.'), a('min', 'Sets the minimum value.', '0'), a('max', 'Sets the maximum value.', '100'), a('value', 'Sets the initial value.', '50'), a('decimals', 'Sets the maximum displayed decimal places.', '1'), a('suffix', 'Appends text to the displayed value.'), a('fill', 'Fills the track from the minimum to the thumb.', 'false', 'boolean'), a('steps', 'Sets the number of discrete positions; minimum two.'), a('labels', 'Sets a JSON array of labels for discrete positions.', '[]', 'code')] },
  { tag: 'select', icon: 'chevron', description: 'Single or multi-select with search, icons, descriptions, and form values.', markup: `<se-select options='[{"id":"one","label":"First option","icon":"check"},{"id":"two","label":"Second option"}]'></se-select>`, attributes: [a('label', 'Sets the field label.'), a('name', 'Names the submitted hidden input.'), a('value', 'Sets selected option IDs, comma-separated for multiple.'), a('placeholder', 'Sets the empty trigger text.', 'Choose an option...'), a('options', 'Sets the option array.', '[]', 'code'), a('size', 'Uses the compact control and menu treatment.', '', 'select', ['small']), a('multiple', 'Enables multi-select behavior.', 'false', 'boolean'), a('searchable', 'Adds option filtering.', 'false', 'boolean'), a('clearable', 'Adds a clear action to single select.', 'false', 'boolean'), a('disabled', 'Disables the select.', 'false', 'boolean')] },
  { tag: 'segmented-control', icon: 'toggle-left', description: 'Animated single-choice control with text, icons, or both.', markup: `<se-segmented-control value="grid" options='[{"id":"grid","label":"Grid","icon":"dashboard"},{"id":"list","label":"List","icon":"list"},{"id":"compact","icon":"table","ariaLabel":"Compact"}]'></se-segmented-control>`, attributes: [a('label', 'Adds a visible group label.'), a('aria-label', 'Labels the group when no visible label is used.', 'Choose an option'), a('name', 'Names the submitted radio group.'), a('value', 'Sets the selected option id.'), a('options', 'Sets options with an id and optional label, icon, ariaLabel, and disabled state.', '[]', 'code'), a('disabled', 'Disables every option.', 'false', 'boolean')] },
  { tag: 'layout-brand', icon: 'package', contexts: sidebarContext, description: 'Reusable layout identity for sidebars and top bars.', markup: '<se-layout-brand icon="assets/WheelWizard_icon.svg" compact-icon="assets/WheelWizard_compact_icon.svg" collapsible></se-layout-brand>', attributes: [a('icon', 'Sets the full-size SVG brand artwork or a bundled icon name.', 'dashboard'), a('compact-icon', 'Sets the compact SVG artwork; falls back to icon.', ''), a('dark-icon', 'Optional full-size artwork for dark mode.'), a('compact-dark-icon', 'Optional compact artwork for dark mode.'), a('label', 'Sets the brand name; omit it when the artwork already includes the name.'), a('href', 'Makes the brand link to a destination such as the homepage.'), a('compact', 'Shows the compact artwork and hides the label.', 'false', 'boolean'), a('collapsible', 'Adds the desktop layout collapse button.', 'false', 'boolean')] },
  { tag: 'sidebar', icon: 'panel-left-close', previewSurface: 'gray', description: 'Layout navigation shell with native header, section, and footer regions.', markup: '<se-sidebar><section><se-sidebar-chapter title="Workspace"><se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button></se-sidebar-chapter></section></se-sidebar>', attributes: [a('closed', 'Hides the entire sidebar while preserving its layout position.', 'false', 'boolean'), a('collapsible', 'Adds the circular edge collapse control.', 'false', 'boolean'), a('collapsed', 'Starts the sidebar collapsed.', 'false', 'boolean'), a('overlay', 'Keeps the sidebar over page content when expanded or collapsed.', 'false', 'boolean'), a('layout-mode', 'Sets responsive behavior or viewport visibility.', 'always', 'select', ['always', 'responsive', 'mobile-only', 'desktop-only']), a('content', 'Sets native header, section, footer, and navigation markup.', '<section><se-sidebar-chapter title="Workspace"><se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button></se-sidebar-chapter></section>', 'content')] },
  { tag: 'sidebar-toggle', icon: 'menu', description: 'Square menu button that opens or closes a targeted sidebar.', markup: '<se-sidebar-toggle for="example-sidebar"></se-sidebar-toggle>', attributes: [a('for', 'Targets a sidebar by its HTML id.'), a('label', 'Sets the accessible button label.'), a('layout-mode', 'Limits the toggle by viewport.', 'always', 'select', ['always', 'mobile-only', 'desktop-only']), a('floating', 'Positions the mobile toggle over a layout without a top bar.', 'false', 'boolean')] },
  { tag: 'sidebar-chapter', icon: 'list-header', contexts: sidebarContext, description: 'Named group of sidebar actions with optional animated disclosure.', markup: '<se-sidebar-chapter title="Workspace" collapsible><se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-chapter>', attributes: [a('title', 'Sets the chapter heading.', 'Chapter'), a('collapsible', 'Makes the heading toggle its contents.', 'false', 'boolean'), a('collapsed', 'Starts a collapsible chapter closed.', 'false', 'boolean'), a('content', 'Sets the chapter actions.', '<se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button>', 'content')] },
  { tag: 'sidebar-button', icon: 'mouse-pointer', contexts: sidebarContext, description: 'Navigation action used by sidebar sections.', markup: '<se-sidebar-button label="Dashboard" icon="dashboard" href="#dashboard"></se-sidebar-button>', attributes: [a('label', 'Sets the navigation label.', 'Navigation item'), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('href', 'Renders the action as a link.'), a('active', 'Applies the selected state.', 'false', 'boolean'), a('disabled', 'Disables a button without an href.', 'false', 'boolean')] },
  { tag: 'sidebar-group', icon: 'list-start', contexts: sidebarContext, description: 'Nested, collapsible navigation group with an optional separate destination.', markup: '<se-sidebar-group label="Form elements" icon="text-input"><se-sidebar-button label="Input" icon="text-input"></se-sidebar-button><se-sidebar-button label="Checkbox" icon="checkbox"></se-sidebar-button></se-sidebar-group>', attributes: [a('variant', 'Changes the supporting treatment.', 'default', 'select', ['default', 'recent']), a('label', 'Sets the group label.', 'Group'), a('icon', 'Sets the group icon.', '', 'select', icons), a('href', 'Adds a separate destination to the group label.'), a('subtext', 'Adds context such as “Recent”.'), a('collapsed', 'Starts the group closed.', 'false', 'boolean'), a('content', 'Sets the nested sidebar buttons.', '<se-sidebar-button label="Input" icon="text-input"></se-sidebar-button><se-sidebar-button label="Checkbox" icon="checkbox"></se-sidebar-button>', 'content')] },
  { tag: 'split-button', icon: 'chevron', description: 'Primary action with selectable or immediate alternatives.', markup: `<se-split-button text="Publish" icon="send" options='[{"id":"publish","label":"Publish","icon":"send"},{"id":"draft","label":"Save draft","icon":"file"}]'></se-split-button>`, attributes: [a('variant', 'Sets the visual button style.', 'brand', 'select', ['primary', 'brand', 'secondary', 'ghost', 'danger']), a('type', 'Sets the native primary-button type.', 'button', 'select', ['button', 'submit', 'reset']), a('icon', 'Sets the fallback primary-action icon.', '', 'select', icons), a('text', 'Sets the fallback primary-action text.', 'Action'), a('label', 'Keeps compatibility with the former fallback-label attribute.'), a('disabled', 'Disables both button segments.', 'false', 'boolean'), a('aria-label', 'Overrides the accessible primary-action label.'), a('direct', 'Runs a selected menu action immediately instead of replacing the primary action.', 'false', 'boolean'), a('options', 'Sets actions with an id, label, icon, and optional disabled state.', '[]', 'code')] },
  { tag: 'tree-item', icon: 'file', description: 'Folder or file row for use inside a tree.', markup: '<se-tree-item type="file" label="README.md" meta="2 KB"></se-tree-item>', attributes: [a('type', 'Chooses folder disclosure or file action behavior.', 'file', 'select', ['file', 'folder']), a('label', 'Sets the item label.', 'File'), a('icon', 'Sets the item icon.', '', 'select', icons), a('meta', 'Adds trailing metadata.'), a('href', 'Renders a file item as a link.'), a('open', 'Expands a folder initially.', 'false', 'boolean'), a('selected', 'Marks the current item.', 'false', 'boolean'), a('disabled', 'Disables interaction.', 'false', 'boolean'), a('content', 'Sets nested items for a folder.', '', 'content')] },
  { tag: 'thought-train', icon: 'activity', description: 'Timeline marker for an AI thought or reasoning step with optional disclosure.', markup: '<se-thought-train title="Planning" collapsible>Checking the available context.</se-thought-train>', attributes: [a('variant', 'Sets the marker color family.', 'brand', 'select', variants), a('title', 'Sets the thought title.', 'Thought process'), a('icon', 'Sets the marker icon.', 'activity', 'select', icons), a('collapsible', 'Makes the thought content expandable.', 'false', 'boolean'), a('open', 'Starts a collapsible thought expanded.', 'false', 'boolean'), a('clickable', 'Makes the thought heading a button.', 'false', 'boolean'), a('content', 'Sets the thought HTML.', 'Checking the available context.', 'content')] },
  { tag: 'text', icon: 'type', description: 'Body and supporting typography.', markup: '<se-text>Body copy</se-text>', attributes: [a('muted', 'Uses the muted text color.', 'false', 'boolean'), a('small', 'Uses the smaller supporting size.', 'false', 'boolean'), a('content', 'Sets the text content.', 'Body copy', 'content')] },
  { tag: 'theme-switch', icon: 'sun', description: 'Two- or three-way theme choice that submits light, system, or dark.', markup: '<se-theme-switch mode="ternary" variant="segmented" value="system" name="theme"></se-theme-switch>', attributes: [a('variant', 'Chooses switch, segmented, or compact button presentation.', 'switch', 'select', ['switch', 'segmented', 'button']), a('mode', 'Offers light/dark or light/system/dark.', 'binary', 'select', ['binary', 'ternary']), a('label', 'Adds a visible label.'), a('aria-label', 'Labels an otherwise unlabeled theme control.', 'Theme'), a('name', 'Names the submitted form field.'), a('value', 'Sets the selected theme.', 'light', 'select', ['light', 'system', 'dark']), a('disabled', 'Disables theme selection.', 'false', 'boolean')] },
  { tag: 'time-picker', icon: 'clock', description: 'Scrollable and typeable time picker backed by a named hidden input.', markup: '<se-time-picker></se-time-picker>', attributes: [a('label', 'Sets the field label.', 'Time'), a('name', 'Names the submitted field.'), a('value', 'Sets a 24-hour HH:MM value.'), a('step', 'Sets the minute step in seconds.', '300'), a('placeholder', 'Sets the empty trigger text.', 'Choose a time'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'topbar', icon: 'panel-left-close', previewSurface: 'gray', description: 'Horizontal page-layout bar for native start, center, and end regions.', markup: '<se-topbar><section data-start><se-layout-brand icon="package" label="Workspace"></se-layout-brand></section><section data-center></section><section data-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></section></se-topbar>', attributes: [a('layout-mode', 'Limits the top bar by viewport.', 'always', 'select', ['always', 'mobile-only', 'desktop-only']), a('content', 'Composes the top-bar regions.', '<section data-start><se-layout-brand icon="package" label="Workspace"></se-layout-brand></section><section data-center></section><section data-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></section>', 'content')] },
  { tag: 'title', icon: 'type', description: 'Consistent page, section, card, and sidebar headings.', markup: '<se-title level="section">Section title</se-title>', attributes: [a('level', 'Sets the heading style.', 'section', 'select', ['page', 'section', 'card', 'sidebar']), a('content', 'Sets the title text.', 'Section title', 'content')] },
  { tag: 'tooltip', icon: 'message-square', description: 'CSS-positioned contextual text for hover and keyboard focus.', markup: '<se-tooltip content="Helpful context"><se-button text="Hover me"></se-button></se-tooltip>', attributes: [a('content', 'Sets the tooltip bubble text.'), a('child-content', 'Sets the trigger HTML.', '<se-button text="Hover me"></se-button>', 'content')] },
  { tag: 'wysiwyg', icon: 'edit', description: 'Rich-text editor with styled editing and HTML/Markdown source views.', markup: '<se-wysiwyg label="Body" format="both">## A formatted heading</se-wysiwyg>', attributes: [a('label', 'Sets the editor label.'), a('name', 'Names the backing native textarea.'), a('placeholder', 'Sets the empty editor hint.', 'Start writing...'), a('value', 'Sets the initial HTML or Markdown source.', '', 'code'), a('format', 'Sets the accepted source format: markdown (default), html, or both.', 'markdown', 'select', ['markdown', 'html', 'both']), a('disabled', 'Disables editing and toolbar actions.', 'false', 'boolean')] },
];

const sidebarIcons = { badge: 'badge', blockquote: 'blockquote', card: 'card', checkbox: 'checkbox', 'chat-context': 'info', 'chat-message': 'message-square', 'datetime-picker': 'calendar-clock', drawer: 'panel-right', input: 'text-input', 'list-header': 'list-header', 'list-row': 'list-row', radio: 'radio', range: 'range', 'split-button': 'list-start', 'thought-train': 'activity', tooltip: 'message-help', wysiwyg: 'wysiwyg' };
const modal = components.find(({ tag }) => tag === 'modal');
modal.attributes = modal.attributes.filter(({ name }) => name !== 'centered');
modal.attributes.find(({ name }) => name === 'subtitle').description = 'Adds supporting text below the title.';
const sidebarGroup = components.find(({ tag }) => tag === 'sidebar-group');
Object.assign(sidebarGroup, {
  description: 'Nested navigation group that can optionally also link to its own page.',
  markup: '<se-sidebar-group variant="page" label="Dossiers" icon="folder" href="#dossiers" subtext="Recent"><se-sidebar-button label="Project Atlas" icon="file"></se-sidebar-button><se-sidebar-button label="Project Nova" icon="file"></se-sidebar-button></se-sidebar-group>',
  attributes: [a('variant', 'Chooses a group-only button or separate page and disclosure controls.', 'group', 'select', ['group', 'page']), a('label', 'Sets the group label.', 'Group'), a('icon', 'Sets the group icon.', '', 'select', icons), a('href', 'Sets the destination used by the page variant.'), a('subtext', 'Labels the nested items while the group is open.'), a('collapsed', 'Starts the group closed.', 'false', 'boolean'), a('content', 'Sets the nested sidebar buttons.', '<se-sidebar-button label="Project Atlas" icon="file"></se-sidebar-button><se-sidebar-button label="Project Nova" icon="file"></se-sidebar-button>', 'content')],
});
export const componentCatalog = components.map((component) => ({ ...component, icon: sidebarIcons[component.tag] || component.icon }));
const chatPatterns = [
  { title: 'Group chat', description: 'A shared conversation with participants, activity context, and a composer.', markup: '<div class="demo-chat"><div class="demo-chat__messages"><se-chat-context icon="users">Maya renamed the group to Product launch.</se-chat-context><se-chat-message mode="received" title="Maya" profile timestamp="09:41">The release notes are ready for review.</se-chat-message><se-chat-message mode="received" title="Alex" profile timestamp="09:42">I added the final mobile screenshots.</se-chat-message><se-chat-message mode="sent" title="You" timestamp="09:43">Great, I will take a look.</se-chat-message><se-chat-context icon="pin">Maya pinned the launch checklist.</se-chat-context><se-chat-message mode="received" title="Maya" profile timestamp="09:47">Could you sign off before stand-up?</se-chat-message><se-chat-message mode="sent" title="You" timestamp="09:49">Yes, I will leave comments in the document.</se-chat-message></div><div class="demo-chat__composer"><se-input type="textarea" label="Message" autosize placeholder="Write a message..."></se-input><se-button variant="brand" icon="send" aria-label="Send message"></se-button></div></div>' },
  { title: 'Private chat', description: 'A quieter one-to-one exchange with optional profile icons and inline timestamps.', markup: '<div class="demo-chat"><div class="demo-chat__messages"><se-chat-message mode="received" title="Jordan" profile timestamp="10:12">Can you share the latest project brief?</se-chat-message><se-chat-message mode="sent" title="You" timestamp="10:14" timestamp-position="start">Absolutely. I have just sent it over.</se-chat-message><se-chat-message mode="received" title="Jordan" profile timestamp="10:16">Thanks. The revised timeline is much clearer.</se-chat-message><se-chat-message mode="sent" title="You" timestamp="10:18">Good. The only open item is the launch date.</se-chat-message><se-chat-context icon="calendar">A call was scheduled for tomorrow at 09:30.</se-chat-context><se-chat-message mode="received" title="Jordan" profile timestamp="10:21">Perfect, we can settle it then.</se-chat-message></div><div class="demo-chat__composer"><se-input type="textarea" label="Message" autosize placeholder="Reply to Jordan..."></se-input><se-button variant="brand" icon="send" aria-label="Send message"></se-button></div></div>' },
  { title: 'Chatbot', description: 'An AI conversation with model selection, reasoning context, and a prompt composer.', markup: '<div class="demo-chat"><div class="demo-chat__messages"><se-chat-message mode="sent" title="You" timestamp="10:16">Show me how these components could form a project dashboard.</se-chat-message><se-chat-context icon="zap">Model changed to Nova reasoning.</se-chat-context><se-thought-train title="Reviewing the component set" collapsible>Finding components for navigation, status summaries, activity, and forms.</se-thought-train><se-thought-train title="Planning the layout" collapsible>Arranging the examples into a compact dashboard hierarchy.</se-thought-train><se-chat-message mode="received" title="Nova" profile timestamp="10:18"><p>Start with the page layout, then add cards for project status and recent activity.</p><p>A compact form can use the icon-rich select for assignment and priority.</p></se-chat-message><se-chat-message mode="sent" title="You" timestamp="10:20">Can the same layout work on a smaller screen?</se-chat-message><se-thought-train title="Checking responsive behavior" collapsible>Comparing the collapsible sidebar and stacked card patterns.</se-thought-train><se-chat-message mode="received" title="Nova" profile timestamp="10:21"><p>Yes. Collapse the sidebar and let the cards stack into one column.</p><p>The controls already fill their available width, so no separate mobile component is needed.</p></se-chat-message></div><div class="demo-chat__composer"><se-select value="nova" options=\'[{"id":"nova","label":"Nova","description":"Fast everyday assistant","icon":"zap"},{"id":"atlas","label":"Atlas","description":"Deep analysis model","icon":"activity"}]\'></se-select><se-input type="textarea" autosize placeholder="Ask anything..."></se-input><se-button variant="brand" icon="send" aria-label="Send prompt"></se-button></div></div>' },
];

export const patternCatalog = [{
  tag: 'page-layout',
  icon: 'panel-left-close',
  description: 'Standard page shells composed from sidebar, top-bar, navigation, profile, and theme components.',
  examples: [
    { title: 'Simple sidebar', description: 'A minimal desktop sidebar paired with a mobile-only top bar.', markup: '<div class="se-page-layout se-page-layout--topbar"><se-topbar layout-mode="mobile-only"><section data-start><se-sidebar-toggle for="simple-sidebar"></se-sidebar-toggle><se-layout-brand icon="dashboard" label="Dashboard"></se-layout-brand></section></se-topbar><div class="se-page-layout__row"><se-sidebar id="simple-sidebar" layout-mode="responsive"><section><se-sidebar-chapter title="Navigation"><se-sidebar-button label="Dashboard" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-chapter></section></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dashboard</se-title></main></div></div>' },
    { title: 'Collapsed sidebar', description: 'The desktop sidebar collapses to a compact rail while remaining part of the page layout.', markup: '<div class="se-page-layout se-page-layout--topbar"><se-topbar layout-mode="mobile-only"><section data-start><se-sidebar-toggle for="edge-sidebar"></se-sidebar-toggle><se-layout-brand icon="dashboard" label="Overview"></se-layout-brand></section><section data-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></section></se-topbar><div class="se-page-layout__row"><se-sidebar id="edge-sidebar" layout-mode="responsive" collapsible><section><se-sidebar-chapter title="Workspace"><se-sidebar-button label="Overview" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-chapter></section><footer layout-mode="desktop-only"><se-profile name="Sarah Jenkins" subtitle="Administrator" initials="SJ"></se-profile></footer></se-sidebar><main class="se-page-layout__content"><se-title level="page">Overview</se-title></main></div></div>' },
    { title: 'Application sidebar', description: 'A branded desktop sidebar with a compact mobile top bar and divided navigation chapters.', markup: '<div class="se-page-layout se-page-layout--topbar"><se-topbar layout-mode="mobile-only"><section data-start><se-sidebar-toggle for="application-sidebar"></se-sidebar-toggle><se-layout-brand icon="assets/WheelWizard_icon.svg" compact-icon="assets/WheelWizard_compact_icon.svg"></se-layout-brand></section><section data-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></section></se-topbar><div class="se-page-layout__row"><se-sidebar id="application-sidebar" layout-mode="responsive"><header layout-mode="desktop-only"><se-layout-brand icon="assets/WheelWizard_icon.svg" compact-icon="assets/WheelWizard_compact_icon.svg" collapsible></se-layout-brand></header><section><se-sidebar-chapter title="Navigation"><se-sidebar-group variant="page" label="Dossiers" icon="folder" href="#dossiers" subtext="Recent"><se-sidebar-button label="Project Atlas" icon="file"></se-sidebar-button><se-sidebar-button label="Project Nova" icon="file"></se-sidebar-button></se-sidebar-group></se-sidebar-chapter><se-sidebar-chapter title="Account"><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-chapter></section><footer layout-mode="desktop-only"><se-profile name="Sarah Jenkins" subtitle="Administrator" initials="SJ"></se-profile></footer></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dossiers</se-title></main></div></div>' },
    { title: 'Responsive top bar', description: 'The mobile top bar keeps navigation and profile actions compact and reveals search on demand; its hamburger sidebar overlays desktop content when open.', markup: '<div class="se-page-layout se-page-layout--topbar"><se-topbar><section data-start><se-sidebar-toggle for="windowed-sidebar"></se-sidebar-toggle><se-layout-brand icon="assets/WheelWizard_icon.svg" compact-icon="assets/WheelWizard_compact_icon.svg"></se-layout-brand></section><section data-center layout-mode="desktop-only"><se-input type="search" placeholder="Search workspace..."></se-input></section><section data-end><se-button variant="ghost" icon="search" aria-label="Search" layout-mode="mobile-only" data-mobile-search-toggle></se-button><se-profile name="Sarah Jenkins" initials="SJ" clickable></se-profile></section><section data-mobile-search hidden><se-input type="search" placeholder="Search workspace..."></se-input></section></se-topbar><div class="se-page-layout__row"><se-sidebar id="windowed-sidebar" layout-mode="responsive" overlay closed><section><se-sidebar-chapter title="Navigation"><se-sidebar-button label="Dashboard" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-chapter></section></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dashboard</se-title></main></div></div>' },
  ],
}, {
  tag: 'chats',
  icon: 'message-square',
  description: 'Composable conversation patterns for group chats, private messages, and AI assistants.',
  examples: chatPatterns,
}, {
  tag: 'file-system',
  icon: 'folder',
  description: 'Three ways to present folders and files using tables, trees, or cards.',
  examples: [
    { title: 'Hierarchical table', description: 'A dense overview with metadata columns and optional guide lines for nested files.', markup: '<se-collection type="table" columns="minmax(12rem, 2fr) 1fr auto"><se-list-header><span>Name</span><span>Modified</span><span>Size</span></se-list-header><se-list-row><strong>Source</strong><span>Today</span><small>3 items</small></se-list-row><se-list-row level="1" guides><span>components</span><span>Today</span><small>2 items</small></se-list-row><se-list-row level="2" guides><span>card.js</span><span>10:42</span><small>4 KB</small></se-list-row><se-list-row level="2" guides><span>tree.js</span><span>09:18</span><small>2 KB</small></se-list-row><se-list-row level="1" guides><span>index.js</span><span>Yesterday</span><small>6 KB</small></se-list-row></se-collection>' },
    { title: 'Folder tree', description: 'A compact navigational hierarchy with native expandable folders.', markup: '<se-collection type="tree"><se-tree-item type="folder" label="Source" open><se-tree-item type="folder" label="components" open><se-tree-item type="file" label="card.js" meta="4 KB"></se-tree-item><se-tree-item type="file" label="tree.js" meta="2 KB" selected></se-tree-item></se-tree-item><se-tree-item type="file" label="index.js" meta="6 KB"></se-tree-item></se-tree-item><se-tree-item type="folder" label="Docs"><se-tree-item type="file" label="README.md"></se-tree-item></se-tree-item></se-collection>' },
    { title: 'Folder and file cards', description: 'Folders and files form distinct sections, with two compact folder cards per row and full-width file cards.', markup: '<div class="demo-file-grid"><se-title class="demo-file-section-title" level="sidebar">Folders</se-title><se-folder-card title="Source" items="3"></se-folder-card><se-folder-card title="Docs" items="8"></se-folder-card><se-folder-card title="Assets" items="24" tone="important"></se-folder-card><se-folder-card title="Tests" items="12" tone="success"></se-folder-card><se-title class="demo-file-section-title demo-file-section-title--divided" level="sidebar">Files</se-title><se-file-card filename="README.md" subtext="12 KB · Updated today" clickable></se-file-card><se-file-card filename="package.json" subtext="2 KB · Updated yesterday" clickable></se-file-card></div>' },
  ],
}, {
  tag: 'forms',
  icon: 'text-input',
  description: 'Complete form compositions for account, project, publishing, and environment workflows.',
  examples: [
    { title: 'Account details', description: 'Profile fields with saved values, a validation error, a disabled identifier, and standard actions.', markup: `<form class="demo-form" onsubmit="return false"><header><se-title level="section">Account details</se-title><se-text muted>Update the information shown to your team.</se-text></header><div class="demo-form-grid"><se-input label="Full name" name="full_name" value="Sarah Jenkins" required></se-input><se-input type="email" label="Email address" name="email" value="sarah@old-domain" error="Enter a complete email address."></se-input><se-phone-input label="Phone number" name="phone" country="NL"></se-phone-input><se-input label="Workspace ID" value="workspace_2841" disabled hint="Assigned automatically."></se-input><se-select class="demo-form-wide" label="Role" name="role" value="admin" options='[{"id":"admin","label":"Administrator","icon":"shield-alert"},{"id":"editor","label":"Editor","icon":"edit"},{"id":"viewer","label":"Viewer","icon":"eye"}]'></se-select><se-checkbox class="demo-form-wide" name="updates" label="Email me product updates" checked></se-checkbox></div><footer class="demo-form-actions"><se-button variant="secondary" text="Cancel"></se-button><se-button variant="brand" type="submit" icon="check" text="Save changes"></se-button></footer></form>` },
    { title: 'New project', description: 'Project setup with searchable ownership, a date, visual settings, and a selectable split-button action.', markup: `<form class="demo-form" onsubmit="return false"><header><se-title level="section">Create project</se-title><se-text muted>Set the basics before inviting collaborators.</se-text></header><div class="demo-form-grid"><se-input class="demo-form-wide" label="Project name" name="project_name" placeholder="Project Northstar" required></se-input><se-input class="demo-form-wide" type="textarea" label="Description" name="description" autosize hint="A short summary for the project overview."></se-input><se-select label="Owner" name="owner" searchable value="sarah" options='[{"id":"sarah","label":"Sarah Jenkins","icon":"user"},{"id":"maya","label":"Maya Chen","icon":"user"}]'></se-select><se-date-picker label="Target date" name="target_date"></se-date-picker><se-color-picker label="Project color" name="color" value="#2563eb" mode="inline"></se-color-picker><se-range label="Priority" name="priority" min="1" max="5" value="3" steps="5" labels='["Low","","Medium","","High"]'></se-range></div><footer class="demo-form-actions"><se-button variant="secondary" text="Cancel"></se-button><se-split-button type="submit" text="Create project" icon="package" options='[{"id":"create","label":"Create project","icon":"package"},{"id":"template","label":"Create as template","icon":"copy"}]'></se-split-button></footer></form>` },
    { title: 'Publish article', description: 'A content workflow with rich text, attachments, scheduling, and direct alternative actions.', markup: `<form class="demo-form" onsubmit="return false"><header><se-title level="section">Publish article</se-title><se-text muted>Prepare the article and choose how to release it.</se-text></header><div class="demo-form-grid"><se-input class="demo-form-wide" label="Title" name="title" value="Designing calmer interfaces"></se-input><se-wysiwyg class="demo-form-wide" label="Article" name="article" format="both" value="## Start with hierarchy\n\nMake the important action obvious."></se-wysiwyg><se-file-upload class="demo-form-wide" label="Cover image" name="cover" accept="image/*" hint="PNG or JPG up to 10MB"></se-file-upload><se-select label="Category" name="category" value="design" options='[{"id":"design","label":"Design","icon":"palette"},{"id":"engineering","label":"Engineering","icon":"code"}]'></se-select><se-datetime-picker label="Publish at" name="publish_at" variant="combined"></se-datetime-picker><se-checkbox class="demo-form-wide" variant="switch" name="comments" label="Allow comments" checked></se-checkbox></div><footer class="demo-form-actions"><se-button variant="secondary" text="Preview" icon="eye"></se-button><se-split-button direct text="Publish now" icon="send" options='[{"id":"publish","label":"Publish now","icon":"send"},{"id":"schedule","label":"Schedule article","icon":"calendar-clock"},{"id":"draft","label":"Save draft","icon":"file"}]'></se-split-button></footer></form>` },
    { title: 'Environment settings', description: 'Technical settings with radio choices, source configuration, theme selection, and standard actions.', markup: `<form class="demo-form" onsubmit="return false"><header><se-title level="section">Environment settings</se-title><se-text muted>Configure the deployment target and maintenance behavior.</se-text></header><div class="demo-form-grid"><se-input label="Environment" value="Production" disabled hint="Managed by your organization."></se-input><se-select label="Region" name="region" value="eu" options='[{"id":"eu","label":"Europe West","icon":"database"},{"id":"us","label":"US East","icon":"database"}]'></se-select><fieldset class="demo-form-choice-group"><legend>Deployment strategy</legend><se-radio name="strategy" value="rolling" label="Rolling" checked></se-radio><se-radio name="strategy" value="replace" label="Replace all"></se-radio></fieldset><se-time-picker label="Maintenance window" name="maintenance" value="02:00"></se-time-picker><se-theme-switch label="Interface theme" name="theme" mode="ternary" variant="segmented" value="system"></se-theme-switch><se-checkbox variant="switch" name="automatic" label="Enable automatic deployments"></se-checkbox><se-code-editor class="demo-form-wide" label="Environment variables" name="variables" language="text" value="API_URL=https://api.example.com" wrap></se-code-editor></div><footer class="demo-form-actions"><se-button variant="secondary" text="Discard"></se-button><se-button variant="brand" type="submit" icon="check" text="Save settings"></se-button></footer></form>` },
  ],
}];
