const a = (name, description, defaultValue = '', control = 'text', options = []) => ({ name, description, defaultValue, control, options });
const variants = ['gray', 'brand', 'success', 'warning', 'error', 'info', 'important'];
const languages = ['javascript', 'json', 'markdown', 'html', 'css', 'python'];
const icons = ['activity', 'alert', 'bell', 'bold', 'calendar', 'check', 'chevron', 'clock', 'code', 'copy', 'crown', 'dashboard', 'database', 'edit', 'eye', 'eye-off', 'file', 'file-up', 'italic', 'link', 'list', 'list-ordered', 'lock', 'mail', 'menu', 'message-square', 'moon', 'more', 'mouse-pointer', 'package', 'panel-left-close', 'panel-left-open', 'phone', 'search', 'send', 'settings', 'shield-alert', 'sun', 'table', 'toggle-left', 'trash', 'type', 'underline', 'upload', 'user', 'users', 'x', 'zap'];
icons.push('badge', 'blockquote', 'calendar-clock', 'card', 'checkbox', 'folder', 'list-header', 'list-row', 'list-start', 'message-help', 'panel-right', 'radio', 'range', 'text-input', 'wysiwyg');
icons.sort();

const components = [
  { tag: 'badge', icon: 'crown', description: 'Compact status label with optional icon and text.', markup: '<se-badge></se-badge>', attributes: [a('variant', 'Sets the badge color.', 'gray', 'select', variants), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('text', 'Sets the badge text.', 'Badge'), a('aria-label', 'Labels an icon-only badge for assistive technology.')] },
  { tag: 'blockquote', icon: 'message-square', description: 'Highlighted quotation or callout matching the badge variants.', markup: '<se-blockquote>Simple components compose well.</se-blockquote>', attributes: [a('variant', 'Sets the quotation color.', 'brand', 'select', variants), a('content', 'Sets the quotation content.', 'Simple components compose well.', 'content')] },
  { tag: 'button', icon: 'mouse-pointer', description: 'Action button that derives icon-only, text-only, or combined layout from its attributes.', markup: '<se-button></se-button>', attributes: [a('variant', 'Sets the visual button style.', 'primary', 'select', ['primary', 'brand', 'secondary', 'ghost', 'danger', 'label']), a('type', 'Sets the native button type.', 'button', 'select', ['button', 'submit', 'reset']), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('text', 'Sets the visible button label.', 'Button'), a('disabled', 'Disables the native button.', 'false', 'boolean'), a('aria-label', 'Overrides the accessible button label.')] },
  { tag: 'card', icon: 'package', description: 'Surface container for grouping related content.', markup: '<se-card><se-title level="card">Card title</se-title><se-text>Card content</se-text></se-card>', attributes: [a('content', 'Sets the HTML inside the card.', '<se-title level="card">Card title</se-title><se-text>Card content</se-text>', 'content')] },
  { tag: 'checkbox', icon: 'check', description: 'Native checkbox semantics with checkbox, radio, switch, and theme-control presentations.', markup: '<se-checkbox label="Checkbox"></se-checkbox>', attributes: [a('variant', 'Changes the visual style without changing checkbox semantics.', 'checkbox', 'select', ['checkbox', 'radio', 'switch', 'light-dark-switch', 'light-dark-button']), a('label', 'Sets the visible checkbox label.', 'Checkbox'), a('name', 'Names the native field for form submission.'), a('value', 'Sets the submitted value.', 'on'), a('checked', 'Checks the checkbox initially.', 'false', 'boolean'), a('disabled', 'Disables the checkbox.', 'false', 'boolean')] },
  { tag: 'code-editor', icon: 'code', description: 'Syntax-highlighted textarea with line numbers and form submission.', markup: '<se-code-editor language="javascript" value="const ready = true;"></se-code-editor>', attributes: [a('label', 'Adds a label above the editor.'), a('name', 'Names the backing textarea for form submission.'), a('language', 'Selects the highlighting grammar.', 'javascript', 'select', languages), a('value', 'Sets the editor source.', '', 'code'), a('readonly', 'Prevents editing while retaining selection.', 'false', 'boolean'), a('disabled', 'Disables the editor.', 'false', 'boolean'), a('wrap', 'Wraps long visual lines without adding line numbers.', 'false', 'boolean')] },
  { tag: 'code', icon: 'code', description: 'Inline or block syntax-highlighted code display.', markup: '<se-code>npm install github:DirkDoes/simple-elements</se-code>', attributes: [a('language', 'Selects the highlighting grammar.', '', 'select', languages), a('block', 'Uses the block code presentation.', 'false', 'boolean'), a('wrap', 'Wraps long block-code lines.', 'false', 'boolean'), a('content', 'Sets the displayed source.', 'npm install github:DirkDoes/simple-elements', 'content')] },
  { tag: 'date-picker', icon: 'calendar', description: 'Styled calendar picker backed by a named hidden input.', markup: '<se-date-picker></se-date-picker>', attributes: [a('label', 'Sets the field label.', 'Date'), a('name', 'Names the submitted field.'), a('value', 'Sets an ISO date in YYYY-MM-DD format.'), a('min', 'Sets the earliest selectable ISO date.'), a('max', 'Sets the latest selectable ISO date.'), a('locale', 'Controls localized month and date labels.'), a('placeholder', 'Sets the empty trigger text.', 'Choose a date'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'datetime-picker', icon: 'calendar', description: 'Date and time input with combined, separated, and joined flows.', markup: '<se-datetime-picker></se-datetime-picker>', attributes: [a('variant', 'Selects the field and popover layout.', 'combined', 'select', ['combined', 'seperated', 'joined']), a('label', 'Sets the field label.', 'Date and time'), a('name', 'Names the submitted field.'), a('value', 'Sets an ISO local date-time value.'), a('min', 'Sets the earliest selectable date-time.'), a('max', 'Sets the latest selectable date-time.'), a('step', 'Sets the time step in seconds.', '300'), a('locale', 'Controls localized date labels.'), a('placeholder', 'Sets the empty combined trigger text.', 'Choose date and time'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'drawer', icon: 'panel-left-open', description: 'Side panel that can overlay, overlay without blur, or push the page.', markup: '<se-drawer title="Drawer"><se-text>Drawer content</se-text></se-drawer>', action: 'open', attributes: [a('mode', 'Controls how the drawer relates to the page.', 'overlay', 'select', ['overlay', 'overlay-clear', 'push']), a('title', 'Sets the drawer heading.', 'Drawer'), a('open', 'Opens the drawer initially.', 'false', 'boolean'), a('content', 'Sets the drawer body HTML.', '<se-text>Drawer content</se-text>', 'content')] },
  { tag: 'empty-state', icon: 'package', description: 'Centered empty-result message with optional actions.', markup: '<se-empty-state title="No projects yet" text="Create a project to get started." icon="package"><se-button variant="brand" text="Create project"></se-button></se-empty-state>', attributes: [a('variant', 'Sets the icon treatment.', 'gray', 'select', ['gray', 'brand', 'error']), a('icon', 'Sets the empty-state icon.', 'package', 'select', icons), a('title', 'Sets the empty-state title.', 'Nothing here yet'), a('text', 'Sets the supporting message.'), a('content', 'Adds use-case-specific actions or controls.', '<se-button variant="brand" text="Create project"></se-button>', 'content')] },
  { tag: 'file-row', icon: 'file', description: 'File summary row with customizable icon, subtext, and actions.', markup: '<se-file-row filename="report.pdf" subtext="2.4 MB"></se-file-row>', attributes: [a('filename', 'Sets the displayed filename.'), a('subtext', 'Sets supporting text such as size, type, or status.'), a('icon', 'Sets the leading icon.', 'file', 'select', icons), a('action', 'Adds a removal action icon.', '', 'select', ['x', 'trash']), a('clickable', 'Makes the main file area a button.', 'false', 'boolean')] },
  { tag: 'file-upload', icon: 'file-up', description: 'Styled native file input and drag-and-drop target.', markup: '<se-file-upload></se-file-upload>', attributes: [a('label', 'Sets the field label.', 'Dropzone'), a('prompt', 'Sets the main upload prompt.', 'Upload a file'), a('subprompt', 'Sets the secondary prompt.', 'or drag and drop'), a('hint', 'Sets the accepted-file guidance.', 'PNG, JPG, PDF up to 10MB'), a('name', 'Names the native file input.', 'files'), a('multiple', 'Allows multiple files.', 'false', 'boolean'), a('accept', 'Sets the native accepted file types.')] },
  { tag: 'icon', icon: 'zap', description: 'Lucide icon rendered by a stable Simple Elements name.', markup: '<se-icon name="settings"></se-icon>', attributes: [a('name', 'Selects a bundled Lucide icon.', 'alert', 'select', icons)] },
  { tag: 'input', icon: 'type', description: 'Standard input and textarea with type-aware defaults.', custom: true },
  { tag: 'list-header', icon: 'list', description: 'Header row for flexible lists and tables.', markup: '<se-list-header>Recent activity</se-list-header>', attributes: [a('content', 'Sets the header content.', 'Recent activity', 'content')] },
  { tag: 'list-row', icon: 'list', description: 'Flexible row used inside lists and tables.', markup: '<se-list-row><se-icon name="user"></se-icon><span>A user joined</span></se-list-row>', attributes: [a('content', 'Sets the row content.', '<se-icon name="user"></se-icon><span>A user joined</span>', 'content')] },
  { tag: 'list', icon: 'list', description: 'Consistent container for rows that may have different structures.', markup: '<se-list><se-list-header>Activity</se-list-header><se-list-row>First item</se-list-row><se-list-row>Second item</se-list-row></se-list>', attributes: [a('content', 'Sets the list header and rows.', '<se-list-header>Activity</se-list-header><se-list-row>First item</se-list-row><se-list-row>Second item</se-list-row>', 'content')] },
  { tag: 'markdown', icon: 'type', description: 'Safely renders basic Markdown as Simple Elements content.', markup: '<se-markdown source="# Heading\n\nMarkdown content"></se-markdown>', attributes: [a('source', 'Sets the Markdown source.', '', 'code')] },
  { tag: 'menu', icon: 'menu', description: 'Button-triggered action menu with icons and disabled items.', markup: `<se-menu label="More" options='[{"label":"Edit","icon":"edit"},{"label":"Delete","icon":"trash","danger":true}]'></se-menu>`, attributes: [a('label', 'Sets the trigger label.', 'More'), a('options', 'Sets the menu option array.', '[]', 'code')] },
  { tag: 'modal', icon: 'message-square', description: 'Small, medium, or large dialog overlay with configurable actions and icon color.', markup: '<se-modal title="Confirm action"><se-text>Modal content</se-text></se-modal>', action: 'open', attributes: [a('variant', 'Sets the icon color treatment.', 'error', 'select', variants), a('size', 'Sets the dialog layout and width.', 'small', 'select', ['small', 'medium', 'large']), a('title', 'Sets the dialog heading.'), a('subtitle', 'Adds supporting header text to medium and large dialogs.'), a('icon', 'Adds an icon beside the title.', '', 'select', icons), a('centered', 'Centers the small-dialog body.', 'false', 'boolean'), a('cancel-label', 'Sets the cancel action text.', 'Cancel'), a('confirm-label', 'Sets the confirm action text.', 'Confirm'), a('confirm-variant', 'Sets the confirm button variant.', 'brand', 'select', ['primary', 'brand', 'secondary', 'ghost', 'danger']), a('open', 'Opens the modal initially.', 'false', 'boolean'), a('content', 'Sets the modal body HTML.', '<se-text>Modal content</se-text>', 'content')] },
  { tag: 'phone-input', icon: 'phone', description: 'International phone input with every country and calling code.', markup: '<se-phone-input></se-phone-input>', attributes: [a('label', 'Sets the field label.', 'Phone Number'), a('name', 'Names the native telephone input.'), a('country', 'Sets the initial ISO country code.', ''), a('code', 'Selects the initial country by calling code.'), a('placeholder', 'Sets the telephone number placeholder.', '6 12345678')] },
  { tag: 'profile', icon: 'user', description: 'Avatar initials with a name, subtitle, and optional button behavior.', markup: '<se-profile name="Sarah Jenkins" initials="SJ"></se-profile>', attributes: [a('name', 'Sets the displayed name.'), a('subtitle', 'Adds supporting profile text.'), a('initials', 'Sets the avatar initials.'), a('clickable', 'Renders the profile as a button.', 'false', 'boolean')] },
  { tag: 'radio', icon: 'toggle-left', description: 'Native radio semantics with radio, checkbox, switch, and theme-control presentations.', markup: '<se-radio label="Radio option"></se-radio>', attributes: [a('variant', 'Changes the visual style without changing radio semantics.', 'radio', 'select', ['radio', 'checkbox', 'switch', 'light-dark-switch', 'light-dark-button']), a('label', 'Sets the visible radio label.', 'Radio option'), a('name', 'Names the native radio group.'), a('value', 'Sets the submitted value.', 'on'), a('checked', 'Selects the radio initially.', 'false', 'boolean'), a('disabled', 'Disables the radio.', 'false', 'boolean')] },
  { tag: 'range', icon: 'activity', description: 'Native range input with a synchronized value display.', markup: '<se-range></se-range>', attributes: [a('label', 'Sets the field label.', 'Range'), a('name', 'Names the native range input.'), a('min', 'Sets the minimum value.', '0'), a('max', 'Sets the maximum value.', '100'), a('value', 'Sets the initial value.', '50'), a('suffix', 'Appends text to the displayed value.')] },
  { tag: 'select', icon: 'chevron', description: 'Single or multi-select with search, icons, descriptions, and form values.', markup: `<se-select options='[{"id":"one","label":"First option","icon":"check"},{"id":"two","label":"Second option"}]'></se-select>`, attributes: [a('label', 'Sets the field label.'), a('name', 'Names the submitted hidden input.'), a('value', 'Sets selected option IDs, comma-separated for multiple.'), a('placeholder', 'Sets the empty trigger text.', 'Choose an option...'), a('options', 'Sets the option array.', '[]', 'code'), a('multiple', 'Enables multi-select behavior.', 'false', 'boolean'), a('searchable', 'Adds option filtering.', 'false', 'boolean'), a('clearable', 'Adds a clear action to single select.', 'false', 'boolean'), a('disabled', 'Disables the select.', 'false', 'boolean')] },
  { tag: 'sidebar-body', icon: 'panel-left-close', description: 'Scrollable main region inside a sidebar.', markup: '<se-sidebar-body><se-text>Sidebar body</se-text></se-sidebar-body>', attributes: [a('content', 'Sets the body content.', '<se-text>Sidebar body</se-text>', 'content')] },
  { tag: 'sidebar-brand', icon: 'package', description: 'Sidebar identity with an optional sidebar-wide collapse control.', markup: '<se-sidebar-brand label="Simple Elements" collapsible></se-sidebar-brand>', attributes: [a('icon', 'Sets the brand icon.', 'dashboard', 'select', icons), a('label', 'Sets the brand name.', 'Simple Elements'), a('collapsible', 'Adds the sidebar collapse button.', 'false', 'boolean')] },
  { tag: 'sidebar-button', icon: 'mouse-pointer', description: 'Navigation action used by sidebar sections.', markup: '<se-sidebar-button label="Dashboard" icon="dashboard" href="#dashboard"></se-sidebar-button>', attributes: [a('label', 'Sets the navigation label.', 'Navigation item'), a('icon', 'Adds a bundled Lucide icon.', '', 'select', icons), a('href', 'Renders the action as a link.'), a('active', 'Applies the selected state.', 'false', 'boolean'), a('disabled', 'Disables a button without an href.', 'false', 'boolean')] },
  { tag: 'sidebar-footer', icon: 'panel-left-close', description: 'Optional bottom region inside a sidebar.', markup: '<se-sidebar-footer><se-text small>Sidebar footer</se-text></se-sidebar-footer>', attributes: [a('content', 'Sets the footer content.', '<se-text small>Sidebar footer</se-text>', 'content')] },
  { tag: 'sidebar-group', icon: 'list-start', description: 'Nested, collapsible navigation group with an optional separate destination.', markup: '<se-sidebar-group label="Form elements" icon="text-input"><se-sidebar-button label="Input" icon="text-input"></se-sidebar-button><se-sidebar-button label="Checkbox" icon="checkbox"></se-sidebar-button></se-sidebar-group>', attributes: [a('variant', 'Changes the supporting treatment.', 'default', 'select', ['default', 'recent']), a('label', 'Sets the group label.', 'Group'), a('icon', 'Sets the group icon.', '', 'select', icons), a('href', 'Adds a separate destination to the group label.'), a('subtext', 'Adds context such as “Recent”.'), a('collapsed', 'Starts the group closed.', 'false', 'boolean'), a('content', 'Sets the nested sidebar buttons.', '<se-sidebar-button label="Input" icon="text-input"></se-sidebar-button><se-sidebar-button label="Checkbox" icon="checkbox"></se-sidebar-button>', 'content')] },
  { tag: 'sidebar-header', icon: 'panel-left-close', description: 'Optional top region inside a sidebar.', markup: '<se-sidebar-header><se-sidebar-brand label="Simple Elements"></se-sidebar-brand></se-sidebar-header>', attributes: [a('content', 'Sets the header content.', '<se-sidebar-brand label="Simple Elements"></se-sidebar-brand>', 'content')] },
  { tag: 'sidebar-section', icon: 'list-header', description: 'Named group of sidebar actions with optional animated disclosure.', markup: '<se-sidebar-section title="Workspace" collapsible><se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-section>', attributes: [a('title', 'Sets the section heading.', 'Section'), a('collapsible', 'Makes the heading toggle its contents.', 'false', 'boolean'), a('collapsed', 'Starts a collapsible section closed.', 'false', 'boolean'), a('content', 'Sets the section actions.', '<se-sidebar-button label="Dashboard" icon="dashboard"></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button>', 'content')] },
  { tag: 'split-button', icon: 'chevron', description: 'Primary action combined with a selectable action menu.', markup: `<se-split-button options='[{"id":"publish","label":"Publish","icon":"send"},{"id":"draft","label":"Save draft","icon":"file"}]'></se-split-button>`, attributes: [a('label', 'Sets the fallback action label.', 'Action'), a('options', 'Sets the action option array.', '[]', 'code')] },
  { tag: 'table', icon: 'table', description: 'Shared-column data layout built on list headers and rows.', markup: '<se-table columns="2fr 1fr"><se-list-header><span>Name</span><span>Status</span></se-list-header><se-list-row><span>Project Atlas</span><se-badge variant="success" text="Active"></se-badge></se-list-row></se-table>', attributes: [a('columns', 'Sets the shared CSS grid columns.', 'repeat(auto-fit, minmax(8rem, 1fr))'), a('content', 'Sets the table header and rows.', '<se-list-header><span>Name</span><span>Status</span></se-list-header><se-list-row><span>Project Atlas</span><se-badge variant="success" text="Active"></se-badge></se-list-row>', 'content')] },
  { tag: 'text', icon: 'type', description: 'Body and supporting typography.', markup: '<se-text>Body copy</se-text>', attributes: [a('muted', 'Uses the muted text color.', 'false', 'boolean'), a('small', 'Uses the smaller supporting size.', 'false', 'boolean'), a('content', 'Sets the text content.', 'Body copy', 'content')] },
  { tag: 'time-picker', icon: 'clock', description: 'Scrollable and typeable time picker backed by a named hidden input.', markup: '<se-time-picker></se-time-picker>', attributes: [a('label', 'Sets the field label.', 'Time'), a('name', 'Names the submitted field.'), a('value', 'Sets a 24-hour HH:MM value.'), a('step', 'Sets the minute step in seconds.', '300'), a('placeholder', 'Sets the empty trigger text.', 'Choose a time'), a('required', 'Marks the field as required.', 'false', 'boolean'), a('disabled', 'Disables the picker.', 'false', 'boolean')] },
  { tag: 'topbar', icon: 'panel-left-close', description: 'Horizontal page-layout bar composed from start, body, and end regions.', markup: '<se-topbar><se-topbar-start><se-title level="card">Workspace</se-title></se-topbar-start><se-topbar-body></se-topbar-body><se-topbar-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></se-topbar-end></se-topbar>', attributes: [a('content', 'Composes the top-bar regions.', '<se-topbar-start><se-title level="card">Workspace</se-title></se-topbar-start><se-topbar-body></se-topbar-body><se-topbar-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></se-topbar-end>', 'content')] },
  { tag: 'topbar-body', icon: 'panel-left-close', description: 'Flexible center region inside a top bar.', markup: '<se-topbar-body><se-text>Centered content</se-text></se-topbar-body>', attributes: [a('content', 'Sets the center-region content.', '<se-text>Centered content</se-text>', 'content')] },
  { tag: 'topbar-end', icon: 'panel-left-close', description: 'Right-aligned region inside a top bar.', markup: '<se-topbar-end><se-profile name="Sarah Jenkins" initials="SJ"></se-profile></se-topbar-end>', attributes: [a('content', 'Sets the end-region content.', '<se-profile name="Sarah Jenkins" initials="SJ"></se-profile>', 'content')] },
  { tag: 'topbar-start', icon: 'panel-left-close', description: 'Left-aligned region inside a top bar.', markup: '<se-topbar-start><se-title level="card">Workspace</se-title></se-topbar-start>', attributes: [a('content', 'Sets the start-region content.', '<se-title level="card">Workspace</se-title>', 'content')] },
  { tag: 'title', icon: 'type', description: 'Consistent page, section, card, and sidebar headings.', markup: '<se-title level="section">Section title</se-title>', attributes: [a('level', 'Sets the heading style.', 'section', 'select', ['page', 'section', 'card', 'sidebar']), a('content', 'Sets the title text.', 'Section title', 'content')] },
  { tag: 'tooltip', icon: 'message-square', description: 'CSS-positioned contextual text for hover and keyboard focus.', markup: '<se-tooltip content="Helpful context"><se-button text="Hover me"></se-button></se-tooltip>', attributes: [a('content', 'Sets the tooltip bubble text.'), a('child-content', 'Sets the trigger HTML.', '<se-button text="Hover me"></se-button>', 'content')] },
  { tag: 'wysiwyg', icon: 'edit', description: 'Rich-text editor backed by a named native textarea.', markup: '<se-wysiwyg></se-wysiwyg>', attributes: [a('label', 'Sets the editor label.'), a('name', 'Names the backing textarea.'), a('placeholder', 'Sets the empty editor hint.', 'Start writing...'), a('value', 'Sets the initial HTML.', '', 'code'), a('disabled', 'Disables editing and toolbar actions.', 'false', 'boolean')] },
];

const sidebarIcons = { badge: 'badge', blockquote: 'blockquote', card: 'card', checkbox: 'checkbox', 'datetime-picker': 'calendar-clock', drawer: 'panel-right', input: 'text-input', 'list-header': 'list-header', 'list-row': 'list-row', radio: 'radio', range: 'range', 'split-button': 'list-start', tooltip: 'message-help', wysiwyg: 'wysiwyg' };
export const componentCatalog = components.map((component) => ({ ...component, icon: sidebarIcons[component.tag] || component.icon }));
export const patternCatalog = [{
  tag: 'page-layout',
  icon: 'panel-left-close',
  description: 'Standard page shells composed from sidebar, top-bar, navigation, profile, and theme components.',
  examples: [
    { title: 'Simple sidebar', description: 'A minimal navigation rail without a header, footer, or collapse control.', markup: '<div class="se-page-layout"><se-sidebar><se-sidebar-body><se-sidebar-section title="Navigation"><se-sidebar-button label="Dashboard" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-section></se-sidebar-body></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dashboard</se-title></main></div>' },
    { title: 'Edge collapse', description: 'A sidebar without a header can expose its collapse control on the outer edge.', markup: '<div class="se-page-layout"><se-sidebar collapsible><se-sidebar-body><se-sidebar-section title="Workspace"><se-sidebar-button label="Overview" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-section></se-sidebar-body><se-sidebar-footer><se-profile name="Sarah Jenkins" subtitle="Administrator" initials="SJ"></se-profile></se-sidebar-footer></se-sidebar><main class="se-page-layout__content"><se-title level="page">Overview</se-title></main></div>' },
    { title: 'Application sidebar', description: 'A branded, collapsible sidebar with grouped navigation and the user in its footer.', markup: '<div class="se-page-layout"><se-sidebar><se-sidebar-header><se-sidebar-brand label="Acme" icon="dashboard" collapsible></se-sidebar-brand></se-sidebar-header><se-sidebar-body><se-sidebar-section title="Navigation"><se-sidebar-group label="Dossiers" icon="folder" href="#dossiers" subtext="Recent" variant="recent"><se-sidebar-button label="Project Atlas" icon="file"></se-sidebar-button><se-sidebar-button label="Project Nova" icon="file"></se-sidebar-button></se-sidebar-group><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-section></se-sidebar-body><se-sidebar-footer><se-profile name="Sarah Jenkins" subtitle="Administrator" initials="SJ"></se-profile></se-sidebar-footer></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dossiers</se-title></main></div>' },
    { title: 'Top bar and sidebar', description: 'The top bar owns branding and the user, so the sidebar needs only its body.', markup: '<div class="se-page-layout se-page-layout--topbar"><se-topbar><se-topbar-start><se-sidebar-brand label="Acme" icon="dashboard"></se-sidebar-brand></se-topbar-start><se-topbar-body><se-input type="search" placeholder="Search workspace..."></se-input></se-topbar-body><se-topbar-end><se-profile name="Sarah Jenkins" initials="SJ" clickable></se-profile></se-topbar-end></se-topbar><div class="se-page-layout__row"><se-sidebar><se-sidebar-body><se-sidebar-section title="Navigation"><se-sidebar-button label="Dashboard" icon="dashboard" active></se-sidebar-button><se-sidebar-button label="Settings" icon="settings"></se-sidebar-button></se-sidebar-section></se-sidebar-body></se-sidebar><main class="se-page-layout__content"><se-title level="page">Dashboard</se-title></main></div></div>' },
  ],
}];
