import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { icons as allLucideIcons } from 'lucide';
import { iconNames, extraIcons } from '../src/icon-names.js';

const files = [
  'src/helpers.js',
  'src/theme.js',
  'src/icon-names.js',
  'src/syntax.js',
  'src/native-input.js',
  'src/choice.js',
  'src/calendar.js',
  ...((await readFile('src/index.js', 'utf8')).match(/components\/.+?\.js/g) || []).map((file) => `src/${file}`),
];
const source = (await Promise.all(files.map((file) => readFile(file, 'utf8'))))
  .join('\n')
  .replace(/^import .+?;\r?\n/gm, '')
  .replace(/^export /gm, '');
const lucideIcons = Object.fromEntries(Object.values(iconNames).map((name) => [name, extraIcons[name] || allLucideIcons[name]]));

await mkdir('dist', { recursive: true });
await writeFile('dist/simple-elements.js', `// Generated by npm run build. Do not edit.\n(() => {\nconst lucideIcons = ${JSON.stringify(lucideIcons)};\n${source}\n globalThis.SimpleElements = { setBrandTheme, registerIcons };\n})();\n`);

await writeFile('dist/icons-all.js', `// Optional Lucide pack. Load after simple-elements.js.\nSimpleElements.registerIcons(${JSON.stringify(allLucideIcons)});\n`);

// Clean is the base; the default stylesheet adds Flat without adding CSS to JavaScript.
await mkdir('dist/themes', { recursive: true });
for (const theme of ['studio', 'edge']) await writeFile(`dist/themes/${theme}.css`, await readFile(`src/themes/${theme}.css`, 'utf8'));
const flatCss = await readFile('src/themes/flat.css', 'utf8');
await writeFile('dist/themes/flat.css', flatCss);
await writeFile('dist/styles.css', (await readFile('dist/themes/clean.css', 'utf8')) + '\n' + flatCss);

// Author the large showcase pages separately; deploy one static entry point.
let showcase = await readFile('examples/pages/shell.html', 'utf8');
for (const page of ['dashboard', 'input']) {
  showcase = showcase.replace(`<!-- page:${page} -->`, (await readFile(`examples/pages/${page}.html`, 'utf8')).trimStart().trimEnd());
}
await writeFile('examples/index.html', '<!-- Generated by npm run build from examples/pages. -->\n' + showcase);
