import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { icons as allLucideIcons } from 'lucide';
import { iconNames } from '../src/icon-names.js';

const files = [
  'src/helpers.js',
  'src/icon-names.js',
  'src/syntax.js',
  'src/native-input.js',
  ...((await readFile('src/index.js', 'utf8')).match(/components\/.+?\.js/g) || []).map((file) => `src/${file}`),
];
const source = (await Promise.all(files.map((file) => readFile(file, 'utf8'))))
  .join('\n')
  .replace(/^import .+?;\r?\n/gm, '')
  .replace(/^export /gm, '');
const lucideIcons = Object.fromEntries(Object.values(iconNames).map((name) => [name, allLucideIcons[name]]));

await mkdir('dist', { recursive: true });
await writeFile('dist/simple-elements.js', `// Generated by npm run build. Do not edit.\n(() => {\nconst lucideIcons = ${JSON.stringify(lucideIcons)};\n${source}\n})();\n`);
