import { mkdir, readFile, writeFile } from 'node:fs/promises';

const files = [
  'src/helpers.js',
  ...((await readFile('src/index.js', 'utf8')).match(/components\/.+?\.js/g) || []).map((file) => `src/${file}`),
];
const source = (await Promise.all(files.map((file) => readFile(file, 'utf8'))))
  .join('\n')
  .replace(/^import .+?;\r?\n/gm, '')
  .replace(/^export /gm, '');

await mkdir('dist', { recursive: true });
await writeFile('dist/simple-elements.js', `// Generated by npm run build. Do not edit.\n(() => {\n${source}\n})();\n`);
